MusicApp.Models.MyYouTubeService Class Reference
A service class to interact with YouTube Music and YouTube API for various music-related functionalities.
Public Member Functions
async Task< MyShelf< MySong >?> FetchSongShelvesAsync (string query, string? continuationToken)
Fetches song shelves based on a query with an optional continuation token.
async Task< string?> GetAudioStreamUrlAsync (string songId)
Retrieves the audio stream URL for a given song ID.
async Task< ObservableCollection< Playlist > > FetchAllPlaylistsAsync ()
Fetches all playlists associated with the authenticated user.
async Task< ObservableCollection< MySong >?> FetchPlaylistContentAsync (string playlistId)
Fetches the content of a playlist given its ID.
async Task AddNewPlaylist (string title, string? description=null, string privacyStatus="private")
Creates a new playlist on YouTube with the specified title, description, and privacy status.
async Task DeletePlaylistAsync (string playlistId)
Deletes a playlist from YouTube based on the given playlist ID.
async Task AddSongToPlaylist (Playlist playlist, MySong song)
Adds a song to a playlist on YouTube.
async Task RemoveSongFromPlaylist (Playlist playlist, MySong song)
Removes a song from a playlist on YouTube.
async Task< MyShelf< MySong > > FetchPopularSongsAsync (string? nextPageToken)
Fetches popular songs from YouTube, with an optional next page token for pagination.
async Task< ObservableCollection< MySong >?> FetchRadioSongsAsync (string radioPlaylistId)
Fetches songs from a radio playlist on YouTube Music based on its ID.
Static Public Member Functions
static async Task< MyYouTubeService > CreateYoutubeServiceAsync ()
Initializes and creates an instance of MyYouTubeService with all necessary YouTube clients.
static async Task< ObservableCollection< MySong > > FetchSongsAsync (string query, int count)
Fetches songs based on a query with a specified limit on the number of results.
static async Task< MySong?> FetchSongAsync (string query)
Fetches a single song based on a query.
static async Task< SongVideoInfo > FetchSongVideoInfoAsync (string songId)
Fetches video information for a given song ID.
Private Member Functions
void InitializeYoutubeClients ()
Initializes the YouTubeMusicClient and YoutubeClient.
async Task InitializeGoogleYTService ()
Initializes the Google YouTube API service with OAuth2 authentication.
async Task< MyShelf< MySong > > ConvertSongsToMySongsShelf (IEnumerable< Song > songs, string? nextPageToken)
Converts a list of Song objects to a MyShelf<T> containing MySong objects.
async Task< List< Song > > ConvertToSongs< T > (IEnumerable< T > items, Func< T, string > getTitle)
Converts a collection of items to a list of Song objects based on a title extraction function.
async Task< List< Song > > ConvertToSongs (VideoListResponse response)
Converts a VideoListResponse to a list of Song objects.
async Task< List< Song > > ConvertToSongs (PlaylistItemListResponse response)
Converts a PlaylistItemListResponse to a list of Song objects.
Static Private Attributes
static readonly string[] Scopes
static readonly string ApplicationName = "MusicApp"
static YouTubeService _googleYouTubeService = new()
static YouTubeMusicClient _youtubeMusicClient = new()
static YoutubeClient _youtubeClient = new()
Detailed Description
A service class to interact with YouTube Music and YouTube API for various music-related functionalities.
Definition at line 23 of file MyYouTubeService.cs.
Member Function Documentation
AddNewPlaylist()
async Task MusicApp.Models.MyYouTubeService.AddNewPlaylist (string title, string? description = null, string privacyStatus = "private") [inline]
Creates a new playlist on YouTube with the specified title, description, and privacy status.
Parameters
title The title of the new playlist.
description The description of the new playlist. Defaults to an empty string if not provided.
privacyStatus The privacy status of the playlist ("public" or "private").
Definition at line 236 of file MyYouTubeService.cs.
        {
            try
            {
                var newPlaylist = new Playlist
                {
                    Snippet = new PlaylistSnippet
                    {
                        Title = title,
                        Description = description ?? ""
                    },
                    Status = new PlaylistStatus
                    {
                        PrivacyStatus = privacyStatus == "public" ? "public" : "private"
                    }
                };
                var request = _googleYouTubeService.Playlists.Insert(newPlaylist, "snippet,status");
                var response = await request.ExecuteAsync();
                MessageBox.Show($"New playlist created. Title: {response.Snippet.Title}, PlaylistId: {response.Id}", "Playlist Created", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            catch (GoogleApiException ex)
            {
                MessageBox.Show($"An API error occurred: {ex.Message}\n{ex.Error.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"An error occurred: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }
AddSongToPlaylist()
async Task MusicApp.Models.MyYouTubeService.AddSongToPlaylist (Playlist playlist, MySong song) [inline]
Adds a song to a playlist on YouTube.
Parameters
playlist The playlist to which the song will be added.
song The song to add to the playlist.
Definition at line 294 of file MyYouTubeService.cs.
        {
            try
            {
                var newPlaylistItem = new PlaylistItem
                {
                    Snippet = new PlaylistItemSnippet
                    {
                        PlaylistId = playlist.Id,
                        ResourceId = new ResourceId
                        {
                            Kind = "youtube#video",
                            VideoId = song.Id
                        }
                    }
                };
                var request = _googleYouTubeService.PlaylistItems.Insert(newPlaylistItem, "snippet");
                await request.ExecuteAsync();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Failed to add song to playlist: {ex.Message}");
            }
        }
ConvertSongsToMySongsShelf()
async Task< MyShelf< MySong > > MusicApp.Models.MyYouTubeService.ConvertSongsToMySongsShelf (IEnumerable< Song > songs, string? nextPageToken) [inline], [private]
Converts a list of Song objects to a MyShelf<T> containing MySong objects.
Parameters
songs The list of songs to convert.
nextPageToken The continuation token for pagination.
Returns
A MyShelf<T> containing the converted songs and a continuation token.
Definition at line 433 of file MyYouTubeService.cs.
        {
            var mySongs = await Task.WhenAll(songs.Select(async song => MySong.Create(song)));
            return new MyShelf<MySong>(new ObservableCollection<MySong>(mySongs), nextPageToken);
        }
References MusicApp.Models.MySong.Create().
Referenced by MusicApp.Models.MyYouTubeService.FetchPopularSongsAsync().
ConvertToSongs() [1/2]
async Task< List< Song > > MusicApp.Models.MyYouTubeService.ConvertToSongs (PlaylistItemListResponse response) [inline], [private]
Converts a PlaylistItemListResponse to a list of Song objects.
Parameters
response The response containing the playlist item list.
Returns
A list of Song objects.
Definition at line 481 of file MyYouTubeService.cs.
        {
            return await ConvertToSongs(response.Items, item => item.Snippet.Title);
        }
References MusicApp.Models.MyYouTubeService.ConvertToSongs().
ConvertToSongs() [2/2]
async Task< List< Song > > MusicApp.Models.MyYouTubeService.ConvertToSongs (VideoListResponse response) [inline], [private]
Converts a VideoListResponse to a list of Song objects.
Parameters
response The response containing the video list.
Returns
A list of Song objects.
Definition at line 471 of file MyYouTubeService.cs.
        {
            return await ConvertToSongs(response.Items, video => video.Snippet.Title);
        }
References MusicApp.Models.MyYouTubeService.ConvertToSongs().
Referenced by MusicApp.Models.MyYouTubeService.ConvertToSongs(), MusicApp.Models.MyYouTubeService.ConvertToSongs(), and MusicApp.Models.MyYouTubeService.FetchPopularSongsAsync().
ConvertToSongs< T >()
async Task< List< Song > > MusicApp.Models.MyYouTubeService.ConvertToSongs< T > (IEnumerable< T > items, Func< T, string > getTitle) [inline], [private]
Converts a collection of items to a list of Song objects based on a title extraction function.
Template Parameters
T The type of items in the collection.
Parameters
items The collection of items to convert.
getTitle A function to extract the title from each item.
Returns
A list of Song objects.
Definition at line 446 of file MyYouTubeService.cs.
        {
            var songs = new List<Song>();
            var tasks = items.Select(async item =>
            {
                var title = getTitle(item);
                IEnumerable<Song> searchResults = await _youtubeMusicClient.SearchAsync<Song>(title, 1);
                var song = searchResults.FirstOrDefault();
                if (song != null)
                {
                    songs.Add(song);
                }
            }).ToList();
            await Task.WhenAll(tasks);
            return songs;
        }
CreateYoutubeServiceAsync()
static async Task< MyYouTubeService > MusicApp.Models.MyYouTubeService.CreateYoutubeServiceAsync () [inline], [static]
Initializes and creates an instance of MyYouTubeService with all necessary YouTube clients.
Returns
An initialized MyYouTubeService instance.
Definition at line 39 of file MyYouTubeService.cs.
        {
            var service = new MyYouTubeService();
            service.InitializeYoutubeClients();
            await service.InitializeGoogleYTService();
            return service;
        }
Referenced by MusicApp.ViewModels.MainViewModel.InitializeAsync().
DeletePlaylistAsync()
async Task MusicApp.Models.MyYouTubeService.DeletePlaylistAsync (string playlistId) [inline]
Deletes a playlist from YouTube based on the given playlist ID.
Parameters
playlistId The ID of the playlist to be deleted.
Definition at line 271 of file MyYouTubeService.cs.
        {
            try
            {
                var request = _googleYouTubeService.Playlists.Delete(playlistId);
                await request.ExecuteAsync();
                MessageBox.Show($"Playlist with ID {playlistId} deleted.", "Playlist Deleted", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            catch (GoogleApiException ex)
            {
                MessageBox.Show($"An API error occurred: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"An error occurred: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }
FetchAllPlaylistsAsync()
async Task< ObservableCollection< Playlist > > MusicApp.Models.MyYouTubeService.FetchAllPlaylistsAsync () [inline]
Fetches all playlists associated with the authenticated user.
Returns
An ObservableCollection<T> containing the playlists.
Definition at line 150 of file MyYouTubeService.cs.
        {
            var playlists = new List<Playlist>();
            string? nextPageToken = null;
            try
            {
                do
                {
                    var request = _googleYouTubeService.Playlists.List("snippet");
                    request.Mine = true;
                    request.MaxResults = 10;
                    request.PageToken = nextPageToken;
                    var response = await request.ExecuteAsync();
                    playlists.AddRange(response.Items);
                    nextPageToken = response.NextPageToken;
                } while (nextPageToken != null);
            }
            catch (GoogleApiException ex)
            {
                MessageBox.Show($"An API error occurred: {ex.Message}");
            }
            catch (Exception ex)
            {
                MessageBox.Show($"An error occurred: {ex.Message}");
            }
            return new ObservableCollection<Playlist>(playlists);
        }
FetchPlaylistContentAsync()
async Task< ObservableCollection< MySong >?> MusicApp.Models.MyYouTubeService.FetchPlaylistContentAsync (string playlistId) [inline]
Fetches the content of a playlist given its ID.
Parameters
playlistId The ID of the playlist.
Returns
An ObservableCollection<T> containing the songs in the playlist, or null if an error occurs.
Definition at line 197 of file MyYouTubeService.cs.
        {
            try
            {
                var request = _googleYouTubeService.PlaylistItems.List("snippet,contentDetails");
                request.PlaylistId = playlistId;
                request.MaxResults = 200;
                var response = await request.ExecuteAsync();
                var tasks = response.Items.Select(async item =>
                {
                    var itemInfo = await FetchSongVideoInfoAsync(item.ContentDetails.VideoId);
                    var song = MySong.Create(itemInfo);
                    return song;
                });
                var playlistSongs = await Task.WhenAll(tasks);
                return new ObservableCollection<MySong>(playlistSongs);
            }
            catch (GoogleApiException ex)
            {
                MessageBox.Show($"An API error occurred: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                return null;
            }
            catch (Exception ex)
            {
                MessageBox.Show($"An error occurred: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                return null;
            }
        }
References MusicApp.Models.MySong.Create(), and MusicApp.Models.MyYouTubeService.FetchSongVideoInfoAsync().
FetchPopularSongsAsync()
async Task< MyShelf< MySong > > MusicApp.Models.MyYouTubeService.FetchPopularSongsAsync (string? nextPageToken) [inline]
Fetches popular songs from YouTube, with an optional next page token for pagination.
Parameters
nextPageToken The continuation token for pagination.
Returns
A MyShelf<T> containing popular songs and a continuation token.
Definition at line 371 of file MyYouTubeService.cs.
        {
            var trendingVideosRequest = _googleYouTubeService.Videos.List("snippet");
            trendingVideosRequest.Chart = VideosResource.ListRequest.ChartEnum.MostPopular;
            trendingVideosRequest.RegionCode = "US";
            trendingVideosRequest.MaxResults = 20;
            trendingVideosRequest.VideoCategoryId = "10";
            if (nextPageToken != null)
            {
                trendingVideosRequest.PageToken = nextPageToken;
            }
            var trendingVideosResponse = await trendingVideosRequest.ExecuteAsync();
            var songs = await ConvertToSongs(trendingVideosResponse);
            return await ConvertSongsToMySongsShelf(songs, trendingVideosResponse.NextPageToken);
        }
References MusicApp.Models.MyYouTubeService.ConvertSongsToMySongsShelf(), and MusicApp.Models.MyYouTubeService.ConvertToSongs().
Referenced by MusicApp.ViewModels.PlayerViewModel.ExecuteNext().
FetchRadioSongsAsync()
async Task< ObservableCollection< MySong >?> MusicApp.Models.MyYouTubeService.FetchRadioSongsAsync (string radioPlaylistId) [inline]
Fetches songs from a radio playlist on YouTube Music based on its ID.
Parameters
radioPlaylistId The ID of the radio playlist.
Returns
An ObservableCollection<T> containing the songs in the radio playlist, or null if an error occurs.
Definition at line 396 of file MyYouTubeService.cs.
        {
            try
            {
                string playlistBrowseId = _youtubeMusicClient.GetCommunityPlaylistBrowseId(radioPlaylistId);
                CommunityPlaylistInfo playlist = await _youtubeMusicClient.GetCommunityPlaylistInfoAsync(playlistBrowseId);
                var result = new ObservableCollection<MySong>();
                var tasks = playlist.Songs.Select(async playlistSong =>
                {
                    var song = MySong.Create(playlistSong);
                    result.Add(song);
                });
                await Task.WhenAll(tasks);
                return result;
            }
            catch (Google.GoogleApiException ex)
            {
                MessageBox.Show($"An API error occurred: {ex.Message}", "API Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"An error occurred: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            return null;
        }
References MusicApp.Models.MySong.Create().
FetchSongAsync()
static async Task< MySong?> MusicApp.Models.MyYouTubeService.FetchSongAsync (string query) [inline], [static]
Fetches a single song based on a query.
Parameters
query The search query.
Returns
A MySong object if found; otherwise, null.
Definition at line 125 of file MyYouTubeService.cs.
        {
            IEnumerable<Song> songs = await _youtubeMusicClient.SearchAsync<Song>(query, 1);
            if (!songs.Any()) return null;
            return MySong.Create(songs.FirstOrDefault());
        }
References MusicApp.Models.MySong.Create().
Referenced by MusicApp.Models.MySong.GetPlaylistIdAsync().
FetchSongsAsync()
static async Task< ObservableCollection< MySong > > MusicApp.Models.MyYouTubeService.FetchSongsAsync (string query, int count) [inline], [static]
Fetches songs based on a query with a specified limit on the number of results.
Parameters
query The search query.
count The number of songs to fetch.
Returns
An ObservableCollection<T> containing the fetched songs.
Definition at line 113 of file MyYouTubeService.cs.
        {
            IEnumerable<Song> songs = await _youtubeMusicClient.SearchAsync<Song>(query, count);
            var mySongs = await Task.WhenAll(songs.Select(async song => MySong.Create(song)));
            return new ObservableCollection<MySong>(mySongs);
        }
References MusicApp.Models.MySong.Create().
Referenced by MusicApp.Views.HomeView.AddSongsFromAuthorListBoxAsync().
FetchSongShelvesAsync()
async Task< MyShelf< MySong >?> MusicApp.Models.MyYouTubeService.FetchSongShelvesAsync (string query, string? continuationToken) [inline]
Fetches song shelves based on a query with an optional continuation token.
Parameters
query The search query.
continuationToken The continuation token for pagination.
Returns
A MyShelf<T> containing a collection of songs and a continuation token.
Definition at line 96 of file MyYouTubeService.cs.
        {
            IEnumerable<Shelf> shelves = await _youtubeMusicClient.SearchAsync(query, continuationToken, ShelfKind.Songs);
            List<Song> songs = shelves.SelectMany(shelf => shelf.Items).OfType<Song>().ToList();
            continuationToken = shelves.FirstOrDefault()?.NextContinuationToken;
            var mySongs = await Task.WhenAll(songs.Select(async song => MySong.Create(song)));
            return new MyShelf<MySong>(new ObservableCollection<MySong>(mySongs), continuationToken);
        }
References MusicApp.Models.MySong.Create().
FetchSongVideoInfoAsync()
static async Task< SongVideoInfo > MusicApp.Models.MyYouTubeService.FetchSongVideoInfoAsync (string songId) [inline], [static]
Fetches video information for a given song ID.
Parameters
songId The ID of the song.
Returns
A SongVideoInfo object containing video information.
Definition at line 187 of file MyYouTubeService.cs.
        {
            return await _youtubeMusicClient.GetSongVideoInfoAsync(songId);
        }
Referenced by MusicApp.Models.MyYouTubeService.FetchPlaylistContentAsync(), and MusicApp.Views.HomeView.GetRandomSongs().
GetAudioStreamUrlAsync()
async Task< string?> MusicApp.Models.MyYouTubeService.GetAudioStreamUrlAsync (string songId) [inline]
Retrieves the audio stream URL for a given song ID.
Parameters
songId The ID of the song.
Returns
The URL of the audio stream.
Definition at line 138 of file MyYouTubeService.cs.
        {
            var videoId = YoutubeExplode.Videos.VideoId.Parse(songId);
            var streamManifest = await _youtubeClient.Videos.Streams.GetManifestAsync(videoId);
            var audioStreamInfo = streamManifest.GetAudioOnlyStreams().GetWithHighestBitrate();
            return audioStreamInfo?.Url;
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.PlaySelectedSong().
InitializeGoogleYTService()
async Task MusicApp.Models.MyYouTubeService.InitializeGoogleYTService () [inline], [private]
Initializes the Google YouTube API service with OAuth2 authentication.
Definition at line 59 of file MyYouTubeService.cs.
        {
            try
            {
                string credPath = "token.json";
                UserCredential credential;
                using (var stream = new FileStream("credentials.json", FileMode.Open, FileAccess.Read))
                {
                    credential = await GoogleWebAuthorizationBroker.AuthorizeAsync(
                        GoogleClientSecrets.FromStream(stream).Secrets,
                        Scopes,
                        "user",
                        CancellationToken.None,
                        new FileDataStore(credPath, true));
                }
                // Create YouTube Service
                _googleYouTubeService = new YouTubeService(new BaseClientService.Initializer()
                {
                    HttpClientInitializer = credential,
                    ApplicationName = ApplicationName
                });
            }
            catch
            {
                MessageBox.Show("Failed to connect to Google YouTube API");
            }
        }
InitializeYoutubeClients()
void MusicApp.Models.MyYouTubeService.InitializeYoutubeClients () [inline], [private]
Initializes the YouTubeMusicClient and YoutubeClient.
Definition at line 50 of file MyYouTubeService.cs.
        {
            _youtubeMusicClient = new YouTubeMusicClient();
            _youtubeClient = new YoutubeClient();
        }
RemoveSongFromPlaylist()
async Task MusicApp.Models.MyYouTubeService.RemoveSongFromPlaylist (Playlist playlist, MySong song) [inline]
Removes a song from a playlist on YouTube.
Parameters
playlist The playlist from which the song will be removed.
song The song to remove from the playlist.
Definition at line 325 of file MyYouTubeService.cs.
        {
            try
            {
                string? nextPageToken = null;
                PlaylistItem? playlistItem = null;
                // Loop through pages of playlist items until we find the song
                do
                {
                    var playlistItemsRequest = _googleYouTubeService.PlaylistItems.List("id,snippet");
                    playlistItemsRequest.PlaylistId = playlist.Id;
                    playlistItemsRequest.MaxResults = 20;
                    playlistItemsRequest.PageToken = nextPageToken;
                    var playlistItemsResponse = await playlistItemsRequest.ExecuteAsync();
                    playlistItem = playlistItemsResponse.Items
                        .FirstOrDefault(item => item.Snippet.ResourceId.VideoId == song.Id);
                    nextPageToken = playlistItemsResponse.NextPageToken;
                } while (playlistItem == null && !string.IsNullOrEmpty(nextPageToken));
                // If the song is found in the playlist, delete it
                if (playlistItem != null)
                {
                    var deleteRequest = _googleYouTubeService.PlaylistItems.Delete(playlistItem.Id);
                    await deleteRequest.ExecuteAsync();
                }
                else
                {
                    MessageBox.Show("Song not found in the playlist.");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Failed to remove song from playlist: {ex.Message}");
            }
        }
References MusicApp.Models.MySong.Id.
Member Data Documentation
_googleYouTubeService
YouTubeService MusicApp.Models.MyYouTubeService._googleYouTubeService = new() [static], [private]
Definition at line 30 of file MyYouTubeService.cs.
_youtubeClient
YoutubeClient MusicApp.Models.MyYouTubeService._youtubeClient = new() [static], [private]
Definition at line 33 of file MyYouTubeService.cs.
_youtubeMusicClient
YouTubeMusicClient MusicApp.Models.MyYouTubeService._youtubeMusicClient = new() [static], [private]
Definition at line 32 of file MyYouTubeService.cs.
ApplicationName
readonly string MusicApp.Models.MyYouTubeService.ApplicationName = "MusicApp" [static], [private]
Definition at line 29 of file MyYouTubeService.cs.
Scopes
readonly string [] MusicApp.Models.MyYouTubeService.Scopes [static], [private]
Initial value:
= {
            YouTubeService.Scope.Youtube,
            "https://www.googleapis.com/auth/youtube.force-ssl"
        }
Definition at line 25 of file MyYouTubeService.cs.
                                                  {
            YouTubeService.Scope.Youtube,
            "https://www.googleapis.com/auth/youtube.force-ssl"
        };
The documentation for this class was generated from the following file:
Models/MyYouTubeService.cs