MusicApp.ViewModels.PlayerViewModel Class Reference
ViewModel for managing the music player, handling song playback, control commands, and UI bindings.
Public Member Functions
PlayerViewModel (MainViewModel mainViewModel, MyYouTubeService ys)
Initializes a new instance of the PlayerViewModel class, setting up the VLC player, commands, and event handlers.
void ResetIndices ()
Resets the selected song index to its default value (-1).
void ProvidePlayerInfo (ObservableCollection< MySong > songs, int index, string text, string? continuationToken=null)
Provides the player with a new set of songs, selects the specified song, and updates the UI with the provided information text.
async void PlaySelectedSong ()
Plays the currently selected song, fetching its audio stream and metadata, and updating the UI.
void TrackBarSeek_PreviewMouseLeftButtonDown (object sender, System.Windows.Input.MouseButtonEventArgs e)
Handles the event when the user begins dragging the playback slider, pausing time updates.
void TrackBarSeek_PreviewMouseLeftButtonUp (object sender, System.Windows.Input.MouseButtonEventArgs e)
Handles the event when the user releases the playback slider, seeking to the new time in the song.
void TrackBarSeek_ValueChanged (object sender, System.Windows.RoutedPropertyChangedEventArgs< double > e)
Handles the event when the playback slider value changes, updating the current time display.
Public Member Functions inherited from MusicApp.ViewModels.BaseViewModel
void SetPreviousViewModel (BaseViewModel previousViewModel)
Sets the previous ViewModel for navigation purposes.
BaseViewModel GetPreviousViewModel ()
Gets the previous ViewModel for navigation purposes.
Properties
string? ContinuationToken [get, set]
Gets or sets the continuation token for fetching more songs in a playlist or search result.
string? InfoText [get, set]
Gets or sets the informational text displayed in the player (e.g., current playlist or radio station name).
ObservableCollection< MySong > Songs [get, set]
Gets or sets the collection of songs currently loaded in the player.
MySong? SelectedSong [get, set]
Gets or sets the currently selected song in the player.
int SelectedSongIndex [get, set]
Gets or sets the index of the currently selected song in the song collection.
string? CurrentSongName [get, set]
Gets or sets the name of the current song being played.
string? CurrentArtistName [get, set]
Gets or sets the name of the current artist being played.
string? CurrentTime [get, set]
Gets or sets the current playback time of the song in "mm:ss" format.
double TotalTime [get, set]
Gets or sets the total duration of the current song in seconds.
string? FormattedTotalTime [get, set]
Gets or sets the total time of the current song formatted as "mm:ss".
double SliderValue [get, set]
Gets or sets the value of the slider that tracks song playback.
ImageSource? CurrentSongThumbnail [get, set]
Gets or sets the thumbnail image of the current song.
string? PlayPauseText [get, set]
Gets or sets the text displayed on the Play/Pause button.
bool IsPlaying [get, set]
Gets or sets a value indicating whether a song is currently playing.
bool IsSongSelected [get, set]
Gets or sets a value indicating whether a song is currently selected.
ICommand BackCommand [get]
ICommand PlayPauseCommand [get]
ICommand NextCommand [get]
ICommand PreviousCommand [get]
ICommand ShuffleCommand [get]
ICommand AddSongToPlaylistCommand [get]
ICommand RemoveSongFromPlaylistCommand [get]
Private Member Functions
void ExecuteRemoveSongFromPlaylist (object parameter)
Removes a song from the currently selected playlist, with a confirmation prompt.
async void RemoveSongFromPlaylist (object parameter)
Asynchronously removes the specified song from the currently selected playlist.
void ExecuteAddSongToPlaylist (object parameter)
Adds a song to a selected playlist.
async void AddSongToPlaylist (object parameter)
Asynchronously adds the specified song to a selected playlist, allowing the user to choose the target playlist.
void ExecuteShuffleSongs (object parameter)
Shuffles the current list of songs, while keeping the selected song in its position.
void ExecutePlayPause (object parameter)
Toggles between playing and pausing the current song.
async void ExecuteNext (object parameter)
Plays the next song in the list, or loads more songs if at the end of the current list.
void ProcessNewShelf (MyShelf< MySong >? newShelf)
Processes a newly fetched shelf of songs, adding them to the current playlist.
void ExecutePrevious (object parameter)
Plays the previous song in the list, or restarts the current song if at the beginning.
void ExecuteBack (object parameter)
Navigates back to the previous view, making the mini player visible.
void MediaPlayer_Playing (object sender, EventArgs e)
Handles the MediaPlayer Playing event, updating the total song duration and resetting the slider value.
void MediaPlayer_EndReached (object sender, EventArgs e)
Handles the MediaPlayer EndReached event, automatically playing the next song in the list.
void MediaPlayer_EncounteredError (object sender, EventArgs e)
Handles the MediaPlayer EncounteredError event, displaying an error message if media playback fails.
void Timer_Tick (object sender, EventArgs e)
Handles the Timer Tick event, updating the slider value and current time display during playback.
async Task DisplayPicture ()
Asynchronously fetches and displays the thumbnail image for the currently selected song.
Private Attributes
readonly MainViewModel _mainViewModel
MyYouTubeService _youTubeService
LibVLC _libVLC
MediaPlayer _mediaPlayer
DispatcherTimer _timer
bool _isDragging
bool _isPlaying
ObservableCollection< MySong > _songs = new()
MySong? _selectedSong
string? _currentSongName
string? _currentArtistName
string? _currentTime
double _totalTime
string? _formattedTotalTime
double _sliderValue
ImageSource? _currentSongThumbnail
string? _playPauseText
int _selectedSongIndex = -1
bool _isSongSelected
string? _infoText
string? _continuationToken
string? _mixId
Additional Inherited Members
Protected Member Functions inherited from MusicApp.ViewModels.BaseViewModel
void OnPropertyChanged ([CallerMemberName] string propertyName=null)
Raises the PropertyChanged event to notify the UI of a property value change.
bool SetProperty< T > (ref T field, T value, [CallerMemberName] string propertyName=null)
Sets the specified property if the value is different, and raises the PropertyChanged event.
Events inherited from MusicApp.ViewModels.BaseViewModel
PropertyChangedEventHandler PropertyChanged
Occurs when a property value changes.
Detailed Description
ViewModel for managing the music player, handling song playback, control commands, and UI bindings.
Definition at line 29 of file PlayerViewModel.cs.
Constructor & Destructor Documentation
PlayerViewModel()
MusicApp.ViewModels.PlayerViewModel.PlayerViewModel (MainViewModel mainViewModel, MyYouTubeService ys) [inline]
Initializes a new instance of the PlayerViewModel class, setting up the VLC player, commands, and event handlers.
Definition at line 231 of file PlayerViewModel.cs.
        {
            _mainViewModel = mainViewModel;
            _youTubeService = ys;
            Core.Initialize();
            _libVLC = new LibVLC();
            _mediaPlayer = new MediaPlayer(_libVLC);
            _mediaPlayer.Playing += MediaPlayer_Playing;
            _mediaPlayer.EndReached += MediaPlayer_EndReached;
            _mediaPlayer.EncounteredError += MediaPlayer_EncounteredError;
            _timer = new DispatcherTimer
            {
                Interval = TimeSpan.FromSeconds(1)
            };
            _timer.Tick += Timer_Tick;
            Songs = new ObservableCollection<MySong>();
            PlayPauseText = "Play";
            IsSongSelected = false;
            BackCommand = new RelayCommand(ExecuteBack);
            PlayPauseCommand = new RelayCommand(ExecutePlayPause);
            NextCommand = new RelayCommand(ExecuteNext);
            PreviousCommand = new RelayCommand(ExecutePrevious);
            ShuffleCommand = new RelayCommand(ExecuteShuffleSongs);
            AddSongToPlaylistCommand = new RelayCommand(ExecuteAddSongToPlaylist);
            RemoveSongFromPlaylistCommand = new RelayCommand(ExecuteRemoveSongFromPlaylist);
        }
References MusicApp.ViewModels.PlayerViewModel.ExecuteAddSongToPlaylist(), MusicApp.ViewModels.PlayerViewModel.ExecuteBack(), MusicApp.ViewModels.PlayerViewModel.ExecuteNext(), MusicApp.ViewModels.PlayerViewModel.ExecutePlayPause(), MusicApp.ViewModels.PlayerViewModel.ExecutePrevious(), MusicApp.ViewModels.PlayerViewModel.ExecuteRemoveSongFromPlaylist(), MusicApp.ViewModels.PlayerViewModel.ExecuteShuffleSongs(), MusicApp.ViewModels.PlayerViewModel.IsSongSelected, MusicApp.ViewModels.PlayerViewModel.MediaPlayer_EncounteredError(), MusicApp.ViewModels.PlayerViewModel.MediaPlayer_EndReached(), MusicApp.ViewModels.PlayerViewModel.MediaPlayer_Playing(), MusicApp.ViewModels.PlayerViewModel.PlayPauseText, MusicApp.ViewModels.PlayerViewModel.Songs, and MusicApp.ViewModels.PlayerViewModel.Timer_Tick().
Member Function Documentation
AddSongToPlaylist()
async void MusicApp.ViewModels.PlayerViewModel.AddSongToPlaylist (object parameter) [inline], [private]
Asynchronously adds the specified song to a selected playlist, allowing the user to choose the target playlist.
Definition at line 337 of file PlayerViewModel.cs.
        {
            if (parameter is MySong song)
            {
                var dialog = new PlaylistSelectionDialog(_mainViewModel.HomeViewModel.Playlists);
                var selectedPlaylist = dialog.SelectPlaylist();
                if (selectedPlaylist != null)
                {
                    await _mainViewModel.MyYouTubeService.AddSongToPlaylist(selectedPlaylist, song);
                    if (_mainViewModel.HomeViewModel.SelectedPlaylist == selectedPlaylist)
                    {
                        var result = await _mainViewModel.MyYouTubeService.FetchPlaylistContentAsync(selectedPlaylist.Id);
                        if (result != null)
                        {
                            Songs = result;
                            SelectedSongIndex = -1;
                            SelectedSongIndex = Songs.IndexOf(song);
                        }
                    }
                }
                else
                {
                    MessageBox.Show("No playlist selected");
                }
            }
            else
            {
                MessageBox.Show("Song is null");
            }
        }
References MusicApp.ViewModels.PlayerViewModel.SelectedSongIndex, and MusicApp.ViewModels.PlayerViewModel.Songs.
Referenced by MusicApp.ViewModels.PlayerViewModel.ExecuteAddSongToPlaylist().
DisplayPicture()
async Task MusicApp.ViewModels.PlayerViewModel.DisplayPicture () [inline], [private]
Asynchronously fetches and displays the thumbnail image for the currently selected song.
Definition at line 598 of file PlayerViewModel.cs.
        {
            if (SelectedSong != null)
            {
                CurrentSongThumbnail = await ThumbnailHelper.GetHighQualityThumbnailAsync(SelectedSong.Id);
            }
            else
            {
                CurrentSongThumbnail = null;
            }
        }
References MusicApp.ViewModels.PlayerViewModel.CurrentSongThumbnail, ThumbnailHelper.GetHighQualityThumbnailAsync(), MusicApp.Models.MySong.Id, and MusicApp.ViewModels.PlayerViewModel.SelectedSong.
Referenced by MusicApp.ViewModels.PlayerViewModel.PlaySelectedSong().
ExecuteAddSongToPlaylist()
void MusicApp.ViewModels.PlayerViewModel.ExecuteAddSongToPlaylist (object parameter) [inline], [private]
Adds a song to a selected playlist.
Definition at line 329 of file PlayerViewModel.cs.
        {
            AddSongToPlaylist(parameter);
        }
References MusicApp.ViewModels.PlayerViewModel.AddSongToPlaylist().
Referenced by MusicApp.ViewModels.PlayerViewModel.PlayerViewModel().
ExecuteBack()
void MusicApp.ViewModels.PlayerViewModel.ExecuteBack (object parameter) [inline], [private]
Navigates back to the previous view, making the mini player visible.
Definition at line 472 of file PlayerViewModel.cs.
        {
            _mainViewModel.IsMiniPlayerVisible = true;
            _mainViewModel.NavigateBack();
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.PlayerViewModel().
ExecuteNext()
async void MusicApp.ViewModels.PlayerViewModel.ExecuteNext (object parameter) [inline], [private]
Plays the next song in the list, or loads more songs if at the end of the current list.
Definition at line 409 of file PlayerViewModel.cs.
        {
            if (!IsSongSelected)
                return;
            if (SelectedSongIndex >= 0 && SelectedSongIndex < Songs.Count - 1)
            {
                SelectedSongIndex++;
            }
            else if (_mainViewModel.CurrentMusicSource is MainViewModel.MusicSource.Search)
            {
                //var newShelf = await _youTubeService.FetchMixSongsAsync(_mixId, ContinuationToken);
                //ProcessNewShelf(newShelf);
                MessageBox.Show("Not implemented yet.");
            }
            else if (_mainViewModel.CurrentMusicSource is MainViewModel.MusicSource.Popular)
            {
                var newShelf = await _youTubeService.FetchPopularSongsAsync(ContinuationToken);
                ProcessNewShelf(newShelf);
            }
        }
References MusicApp.ViewModels.PlayerViewModel.ContinuationToken, MusicApp.Models.MyYouTubeService.FetchPopularSongsAsync(), MusicApp.ViewModels.PlayerViewModel.IsSongSelected, MusicApp.ViewModels.PlayerViewModel.ProcessNewShelf(), MusicApp.ViewModels.PlayerViewModel.SelectedSongIndex, and MusicApp.ViewModels.PlayerViewModel.Songs.
Referenced by MusicApp.ViewModels.PlayerViewModel.PlayerViewModel().
ExecutePlayPause()
void MusicApp.ViewModels.PlayerViewModel.ExecutePlayPause (object parameter) [inline], [private]
Toggles between playing and pausing the current song.
Definition at line 386 of file PlayerViewModel.cs.
        {
            if (!IsSongSelected)
                return;
            if (_isPlaying)
            {
                _mediaPlayer.Pause();
                PlayPauseText = "Play";
                _timer.Stop();
            }
            else
            {
                _mediaPlayer.Play();
                PlayPauseText = "Pause";
                _timer.Start();
            }
            IsPlaying = !IsPlaying;
        }
References MusicApp.ViewModels.PlayerViewModel.IsPlaying, MusicApp.ViewModels.PlayerViewModel.IsSongSelected, and MusicApp.ViewModels.PlayerViewModel.PlayPauseText.
Referenced by MusicApp.ViewModels.PlayerViewModel.PlayerViewModel().
ExecutePrevious()
void MusicApp.ViewModels.PlayerViewModel.ExecutePrevious (object parameter) [inline], [private]
Plays the previous song in the list, or restarts the current song if at the beginning.
Definition at line 454 of file PlayerViewModel.cs.
        {
            if (!IsSongSelected)
                return;
            if (SelectedSongIndex > 0)
            {
                SelectedSongIndex--;
            }
            else
            {
                _mediaPlayer.Time = 0;
            }
        }
References MusicApp.ViewModels.PlayerViewModel.IsSongSelected, and MusicApp.ViewModels.PlayerViewModel.SelectedSongIndex.
Referenced by MusicApp.ViewModels.PlayerViewModel.PlayerViewModel().
ExecuteRemoveSongFromPlaylist()
void MusicApp.ViewModels.PlayerViewModel.ExecuteRemoveSongFromPlaylist (object parameter) [inline], [private]
Removes a song from the currently selected playlist, with a confirmation prompt.
Definition at line 292 of file PlayerViewModel.cs.
        {
            RemoveSongFromPlaylist(parameter);
        }
References MusicApp.ViewModels.PlayerViewModel.RemoveSongFromPlaylist().
Referenced by MusicApp.ViewModels.PlayerViewModel.PlayerViewModel().
ExecuteShuffleSongs()
void MusicApp.ViewModels.PlayerViewModel.ExecuteShuffleSongs (object parameter) [inline], [private]
Shuffles the current list of songs, while keeping the selected song in its position.
Definition at line 373 of file PlayerViewModel.cs.
        {
            if (SelectedSong != null)
            {
                var selectedSong = SelectedSong;
                Songs.Shuffle();
                SelectedSongIndex = Songs.IndexOf(selectedSong);
            }
        }
References MusicApp.ViewModels.PlayerViewModel.SelectedSong, MusicApp.ViewModels.PlayerViewModel.SelectedSongIndex, and MusicApp.ViewModels.PlayerViewModel.Songs.
Referenced by MusicApp.ViewModels.PlayerViewModel.PlayerViewModel().
MediaPlayer_EncounteredError()
void MusicApp.ViewModels.PlayerViewModel.MediaPlayer_EncounteredError (object sender, EventArgs e) [inline], [private]
Handles the MediaPlayer EncounteredError event, displaying an error message if media playback fails.
Definition at line 544 of file PlayerViewModel.cs.
        {
            MessageBox.Show("Media playback encountered an error.");
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.PlayerViewModel().
MediaPlayer_EndReached()
void MusicApp.ViewModels.PlayerViewModel.MediaPlayer_EndReached (object sender, EventArgs e) [inline], [private]
Handles the MediaPlayer EndReached event, automatically playing the next song in the list.
Definition at line 536 of file PlayerViewModel.cs.
        {
            NextCommand.Execute(null);
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.PlayerViewModel().
MediaPlayer_Playing()
void MusicApp.ViewModels.PlayerViewModel.MediaPlayer_Playing (object sender, EventArgs e) [inline], [private]
Handles the MediaPlayer Playing event, updating the total song duration and resetting the slider value.
Definition at line 524 of file PlayerViewModel.cs.
        {
            if (_mediaPlayer.Media != null && _mediaPlayer.Media.Duration > 0)
            {
                TotalTime = _mediaPlayer.Media.Duration / 1000.0;
                SliderValue = 0;
            }
        }
References MusicApp.ViewModels.PlayerViewModel.SliderValue, and MusicApp.ViewModels.PlayerViewModel.TotalTime.
Referenced by MusicApp.ViewModels.PlayerViewModel.PlayerViewModel().
PlaySelectedSong()
async void MusicApp.ViewModels.PlayerViewModel.PlaySelectedSong () [inline]
Plays the currently selected song, fetching its audio stream and metadata, and updating the UI.
Definition at line 481 of file PlayerViewModel.cs.
        {
            if (SelectedSong == null)
            {
                IsSongSelected = false;
                return;
            }
            IsSongSelected = true;
            string songId = SelectedSong.Id;
            _mainViewModel.SongDatabase?.UpdateSongCount(songId);
            try
            {
                var audioUrl = await _youTubeService.GetAudioStreamUrlAsync(songId);
                if (audioUrl == null)
                {
                    MessageBox.Show("No audio stream found.");
                    return;
                }
                _mediaPlayer.Media = new Media(_libVLC, new Uri(audioUrl));
                _mediaPlayer.Play();
                IsPlaying = true;
                CurrentSongName = SelectedSong.Name;
                CurrentArtistName = string.Join(", ", SelectedSong.Artists.Select(artist => artist.Name));
                await DisplayPicture();
                _timer.Start();
                PlayPauseText = "Pause";
            }
            catch (Exception ex)
            {
                MessageBox.Show($"An error occurred: {ex.Message}");
            }
        }
References MusicApp.Models.MySong.Artists, MusicApp.ViewModels.PlayerViewModel.CurrentArtistName, MusicApp.ViewModels.PlayerViewModel.CurrentSongName, MusicApp.ViewModels.PlayerViewModel.DisplayPicture(), MusicApp.Models.MyYouTubeService.GetAudioStreamUrlAsync(), MusicApp.Models.MySong.Id, MusicApp.ViewModels.PlayerViewModel.IsPlaying, MusicApp.ViewModels.PlayerViewModel.IsSongSelected, MusicApp.Models.MySong.Name, MusicApp.ViewModels.PlayerViewModel.PlayPauseText, and MusicApp.ViewModels.PlayerViewModel.SelectedSong.
ProcessNewShelf()
void MusicApp.ViewModels.PlayerViewModel.ProcessNewShelf (MyShelf< MySong >? newShelf) [inline], [private]
Processes a newly fetched shelf of songs, adding them to the current playlist.
Parameters
newShelf The new shelf of songs to add to the playlist.
Definition at line 435 of file PlayerViewModel.cs.
        {
            if (newShelf != null)
            {
                Application.Current.Dispatcher.Invoke(() =>
                {
                    foreach (var song in newShelf.Items)
                    {
                        Songs.Add(song);
                    }
                });
            }
            ContinuationToken = newShelf?.ContinuationToken;
            SelectedSongIndex++;
        }
References MusicApp.Models.MyShelf< T >.ContinuationToken, MusicApp.ViewModels.PlayerViewModel.ContinuationToken, MusicApp.Models.MyShelf< T >.Items, and MusicApp.ViewModels.PlayerViewModel.SelectedSongIndex.
Referenced by MusicApp.ViewModels.PlayerViewModel.ExecuteNext().
ProvidePlayerInfo()
void MusicApp.ViewModels.PlayerViewModel.ProvidePlayerInfo (ObservableCollection< MySong > songs, int index, string text, string? continuationToken = null) [inline]
Provides the player with a new set of songs, selects the specified song, and updates the UI with the provided information text.
Parameters
songs The collection of songs to load into the player.
index The index of the song to start playing.
text The informational text to display.
continuationToken Optional. A token for fetching more songs if available.
Definition at line 279 of file PlayerViewModel.cs.
        {
            Songs = songs;
            SelectedSongIndex = -1;
            SelectedSongIndex = index;
            SelectedSong = Songs?.ElementAtOrDefault(index);
            InfoText = text;
            ContinuationToken = continuationToken;
        }
References MusicApp.ViewModels.PlayerViewModel.ContinuationToken, MusicApp.ViewModels.PlayerViewModel.InfoText, MusicApp.ViewModels.PlayerViewModel.SelectedSong, MusicApp.ViewModels.PlayerViewModel.SelectedSongIndex, and MusicApp.ViewModels.PlayerViewModel.Songs.
RemoveSongFromPlaylist()
async void MusicApp.ViewModels.PlayerViewModel.RemoveSongFromPlaylist (object parameter) [inline], [private]
Asynchronously removes the specified song from the currently selected playlist.
Definition at line 300 of file PlayerViewModel.cs.
        {
            if (_mainViewModel.CurrentMusicSource != MainViewModel.MusicSource.Playlist)
                return;
            if (parameter is MySong song && _mainViewModel.HomeViewModel.SelectedPlaylist != null)
            {
                var selectedPlaylist = _mainViewModel.HomeViewModel.SelectedPlaylist;
                var confirmation = MessageBox.Show($"Are you sure you want to remove '{song.ArtistAndSongName}' from '{selectedPlaylist.Snippet.Title}'?",
                                                   "Confirm Removal", MessageBoxButton.YesNo);
                if (confirmation == MessageBoxResult.Yes)
                {
                    await _mainViewModel.MyYouTubeService.RemoveSongFromPlaylist(selectedPlaylist, song);
                    Songs.Remove(song);
                    Songs = new(Songs);
                }
            }
            else
            {
                MessageBox.Show("Song or playlist is null");
            }
        }
References MusicApp.ViewModels.PlayerViewModel.Songs.
Referenced by MusicApp.ViewModels.PlayerViewModel.ExecuteRemoveSongFromPlaylist().
ResetIndices()
void MusicApp.ViewModels.PlayerViewModel.ResetIndices () [inline]
Resets the selected song index to its default value (-1).
Definition at line 267 of file PlayerViewModel.cs.
        {
            SelectedSongIndex = -1;
        }
References MusicApp.ViewModels.PlayerViewModel.SelectedSongIndex.
Referenced by MusicApp.ViewModels.MainViewModel.ResetIndices().
Timer_Tick()
void MusicApp.ViewModels.PlayerViewModel.Timer_Tick (object sender, EventArgs e) [inline], [private]
Handles the Timer Tick event, updating the slider value and current time display during playback.
Definition at line 552 of file PlayerViewModel.cs.
        {
            if (!_isDragging && _mediaPlayer.Media != null)
            {
                SliderValue = _mediaPlayer.Time / 1000.0;
                CurrentTime = TimeSpan.FromMilliseconds(_mediaPlayer.Time).ToString(@"mm\:ss");
            }
        }
References MusicApp.ViewModels.PlayerViewModel.CurrentTime, and MusicApp.ViewModels.PlayerViewModel.SliderValue.
Referenced by MusicApp.ViewModels.PlayerViewModel.PlayerViewModel().
TrackBarSeek_PreviewMouseLeftButtonDown()
void MusicApp.ViewModels.PlayerViewModel.TrackBarSeek_PreviewMouseLeftButtonDown (object sender, System::Windows::Input::MouseButtonEventArgs e) [inline]
Handles the event when the user begins dragging the playback slider, pausing time updates.
Definition at line 564 of file PlayerViewModel.cs.
        {
            if (_mediaPlayer.Media != null)
            {
                _isDragging = true;
            }
        }
TrackBarSeek_PreviewMouseLeftButtonUp()
void MusicApp.ViewModels.PlayerViewModel.TrackBarSeek_PreviewMouseLeftButtonUp (object sender, System::Windows::Input::MouseButtonEventArgs e) [inline]
Handles the event when the user releases the playback slider, seeking to the new time in the song.
Definition at line 575 of file PlayerViewModel.cs.
        {
            if (_mediaPlayer.Media != null)
            {
                _isDragging = false;
                _mediaPlayer.Time = (long)SliderValue * 1000;
            }
        }
References MusicApp.ViewModels.PlayerViewModel.SliderValue.
TrackBarSeek_ValueChanged()
void MusicApp.ViewModels.PlayerViewModel.TrackBarSeek_ValueChanged (object sender, System::Windows::RoutedPropertyChangedEventArgs< double > e) [inline]
Handles the event when the playback slider value changes, updating the current time display.
Definition at line 587 of file PlayerViewModel.cs.
        {
            if (_isDragging && _mediaPlayer.Media != null)
            {
                CurrentTime = TimeSpan.FromSeconds(SliderValue).ToString(@"mm\:ss");
            }
        }
References MusicApp.ViewModels.PlayerViewModel.CurrentTime, and MusicApp.ViewModels.PlayerViewModel.SliderValue.
Member Data Documentation
_continuationToken
string? MusicApp.ViewModels.PlayerViewModel._continuationToken [private]
Definition at line 51 of file PlayerViewModel.cs.
_currentArtistName
string? MusicApp.ViewModels.PlayerViewModel._currentArtistName [private]
Definition at line 41 of file PlayerViewModel.cs.
_currentSongName
string? MusicApp.ViewModels.PlayerViewModel._currentSongName [private]
Definition at line 40 of file PlayerViewModel.cs.
_currentSongThumbnail
ImageSource? MusicApp.ViewModels.PlayerViewModel._currentSongThumbnail [private]
Definition at line 46 of file PlayerViewModel.cs.
_currentTime
string? MusicApp.ViewModels.PlayerViewModel._currentTime [private]
Definition at line 42 of file PlayerViewModel.cs.
_formattedTotalTime
string? MusicApp.ViewModels.PlayerViewModel._formattedTotalTime [private]
Definition at line 44 of file PlayerViewModel.cs.
_infoText
string? MusicApp.ViewModels.PlayerViewModel._infoText [private]
Definition at line 50 of file PlayerViewModel.cs.
_isDragging
bool MusicApp.ViewModels.PlayerViewModel._isDragging [private]
Definition at line 36 of file PlayerViewModel.cs.
_isPlaying
bool MusicApp.ViewModels.PlayerViewModel._isPlaying [private]
Definition at line 37 of file PlayerViewModel.cs.
_isSongSelected
bool MusicApp.ViewModels.PlayerViewModel._isSongSelected [private]
Definition at line 49 of file PlayerViewModel.cs.
_libVLC
LibVLC MusicApp.ViewModels.PlayerViewModel._libVLC [private]
Definition at line 33 of file PlayerViewModel.cs.
_mainViewModel
readonly MainViewModel MusicApp.ViewModels.PlayerViewModel._mainViewModel [private]
Definition at line 31 of file PlayerViewModel.cs.
_mediaPlayer
MediaPlayer MusicApp.ViewModels.PlayerViewModel._mediaPlayer [private]
Definition at line 34 of file PlayerViewModel.cs.
_mixId
string? MusicApp.ViewModels.PlayerViewModel._mixId [private]
Definition at line 52 of file PlayerViewModel.cs.
_playPauseText
string? MusicApp.ViewModels.PlayerViewModel._playPauseText [private]
Definition at line 47 of file PlayerViewModel.cs.
_selectedSong
MySong? MusicApp.ViewModels.PlayerViewModel._selectedSong [private]
Definition at line 39 of file PlayerViewModel.cs.
_selectedSongIndex
int MusicApp.ViewModels.PlayerViewModel._selectedSongIndex = -1 [private]
Definition at line 48 of file PlayerViewModel.cs.
_sliderValue
double MusicApp.ViewModels.PlayerViewModel._sliderValue [private]
Definition at line 45 of file PlayerViewModel.cs.
_songs
ObservableCollection<MySong> MusicApp.ViewModels.PlayerViewModel._songs = new() [private]
Definition at line 38 of file PlayerViewModel.cs.
_timer
DispatcherTimer MusicApp.ViewModels.PlayerViewModel._timer [private]
Definition at line 35 of file PlayerViewModel.cs.
_totalTime
double MusicApp.ViewModels.PlayerViewModel._totalTime [private]
Definition at line 43 of file PlayerViewModel.cs.
_youTubeService
MyYouTubeService MusicApp.ViewModels.PlayerViewModel._youTubeService [private]
Definition at line 32 of file PlayerViewModel.cs.
Property Documentation
AddSongToPlaylistCommand
ICommand MusicApp.ViewModels.PlayerViewModel.AddSongToPlaylistCommand [get]
Definition at line 225 of file PlayerViewModel.cs.
{ get; }
BackCommand
ICommand MusicApp.ViewModels.PlayerViewModel.BackCommand [get]
Definition at line 220 of file PlayerViewModel.cs.
{ get; }
ContinuationToken
string? MusicApp.ViewModels.PlayerViewModel.ContinuationToken [get], [set]
Gets or sets the continuation token for fetching more songs in a playlist or search result.
Definition at line 57 of file PlayerViewModel.cs.
        {
            get => _continuationToken;
            set => SetProperty(ref _continuationToken, value);
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.ExecuteNext(), MusicApp.ViewModels.PlayerViewModel.ProcessNewShelf(), and MusicApp.ViewModels.PlayerViewModel.ProvidePlayerInfo().
CurrentArtistName
string? MusicApp.ViewModels.PlayerViewModel.CurrentArtistName [get], [set]
Gets or sets the name of the current artist being played.
Definition at line 130 of file PlayerViewModel.cs.
        {
            get => _currentArtistName;
            set => SetProperty(ref _currentArtistName, value);
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.PlaySelectedSong().
CurrentSongName
string? MusicApp.ViewModels.PlayerViewModel.CurrentSongName [get], [set]
Gets or sets the name of the current song being played.
Definition at line 121 of file PlayerViewModel.cs.
        {
            get => _currentSongName;
            set => SetProperty(ref _currentSongName, value);
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.PlaySelectedSong().
CurrentSongThumbnail
ImageSource? MusicApp.ViewModels.PlayerViewModel.CurrentSongThumbnail [get], [set]
Gets or sets the thumbnail image of the current song.
Definition at line 181 of file PlayerViewModel.cs.
        {
            get => _currentSongThumbnail;
            set => SetProperty(ref _currentSongThumbnail, value);
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.DisplayPicture().
CurrentTime
string? MusicApp.ViewModels.PlayerViewModel.CurrentTime [get], [set]
Gets or sets the current playback time of the song in "mm:ss" format.
Definition at line 139 of file PlayerViewModel.cs.
        {
            get => _currentTime;
            set => SetProperty(ref _currentTime, value);
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.Timer_Tick(), and MusicApp.ViewModels.PlayerViewModel.TrackBarSeek_ValueChanged().
FormattedTotalTime
string? MusicApp.ViewModels.PlayerViewModel.FormattedTotalTime [get], [set]
Gets or sets the total time of the current song formatted as "mm:ss".
Definition at line 163 of file PlayerViewModel.cs.
        {
            get => _formattedTotalTime;
            set => SetProperty(ref _formattedTotalTime, value);
        }
InfoText
string? MusicApp.ViewModels.PlayerViewModel.InfoText [get], [set]
Gets or sets the informational text displayed in the player (e.g., current playlist or radio station name).
Definition at line 66 of file PlayerViewModel.cs.
        {
            get => _infoText;
            set => SetProperty(ref _infoText, value);
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.ProvidePlayerInfo().
IsPlaying
bool MusicApp.ViewModels.PlayerViewModel.IsPlaying [get], [set]
Gets or sets a value indicating whether a song is currently playing.
Definition at line 199 of file PlayerViewModel.cs.
        {
            get => _isPlaying;
            set => SetProperty(ref _isPlaying, value);
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.ExecutePlayPause(), and MusicApp.ViewModels.PlayerViewModel.PlaySelectedSong().
IsSongSelected
bool MusicApp.ViewModels.PlayerViewModel.IsSongSelected [get], [set]
Gets or sets a value indicating whether a song is currently selected.
Definition at line 208 of file PlayerViewModel.cs.
        {
            get => _isSongSelected;
            set
            {
                if (SetProperty(ref _isSongSelected, value))
                {
                    CommandManager.InvalidateRequerySuggested();
                }
            }
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.ExecuteNext(), MusicApp.ViewModels.PlayerViewModel.ExecutePlayPause(), MusicApp.ViewModels.PlayerViewModel.ExecutePrevious(), MusicApp.ViewModels.PlayerViewModel.PlayerViewModel(), and MusicApp.ViewModels.PlayerViewModel.PlaySelectedSong().
NextCommand
ICommand MusicApp.ViewModels.PlayerViewModel.NextCommand [get]
Definition at line 222 of file PlayerViewModel.cs.
{ get; }
PlayPauseCommand
ICommand MusicApp.ViewModels.PlayerViewModel.PlayPauseCommand [get]
Definition at line 221 of file PlayerViewModel.cs.
{ get; }
PlayPauseText
string? MusicApp.ViewModels.PlayerViewModel.PlayPauseText [get], [set]
Gets or sets the text displayed on the Play/Pause button.
Definition at line 190 of file PlayerViewModel.cs.
        {
            get => _playPauseText;
            set => SetProperty(ref _playPauseText, value);
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.ExecutePlayPause(), MusicApp.ViewModels.PlayerViewModel.PlayerViewModel(), and MusicApp.ViewModels.PlayerViewModel.PlaySelectedSong().
PreviousCommand
ICommand MusicApp.ViewModels.PlayerViewModel.PreviousCommand [get]
Definition at line 223 of file PlayerViewModel.cs.
{ get; }
RemoveSongFromPlaylistCommand
ICommand MusicApp.ViewModels.PlayerViewModel.RemoveSongFromPlaylistCommand [get]
Definition at line 226 of file PlayerViewModel.cs.
{ get; }
SelectedSong
MySong? MusicApp.ViewModels.PlayerViewModel.SelectedSong [get], [set]
Gets or sets the currently selected song in the player.
Definition at line 88 of file PlayerViewModel.cs.
        {
            get => _selectedSong;
            set => SetProperty(ref _selectedSong, value);
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.DisplayPicture(), MusicApp.ViewModels.PlayerViewModel.ExecuteShuffleSongs(), MusicApp.ViewModels.PlayerViewModel.PlaySelectedSong(), and MusicApp.ViewModels.PlayerViewModel.ProvidePlayerInfo().
SelectedSongIndex
int MusicApp.ViewModels.PlayerViewModel.SelectedSongIndex [get], [set]
Gets or sets the index of the currently selected song in the song collection.
Definition at line 97 of file PlayerViewModel.cs.
        {
            get => _selectedSongIndex;
            set
            {
                if (SetProperty(ref _selectedSongIndex, value))
                {
                    if (value != -1)
                    {
                        var currentSong = SelectedSong;
                        SelectedSong = Songs?.ElementAtOrDefault(value);
                        if (SelectedSong != null && currentSong != SelectedSong)
                        {
                            PlaySelectedSong();
                        }
                    }
                }
            }
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.AddSongToPlaylist(), MusicApp.ViewModels.PlayerViewModel.ExecuteNext(), MusicApp.ViewModels.PlayerViewModel.ExecutePrevious(), MusicApp.ViewModels.PlayerViewModel.ExecuteShuffleSongs(), MusicApp.ViewModels.PlayerViewModel.ProcessNewShelf(), MusicApp.ViewModels.PlayerViewModel.ProvidePlayerInfo(), and MusicApp.ViewModels.PlayerViewModel.ResetIndices().
ShuffleCommand
ICommand MusicApp.ViewModels.PlayerViewModel.ShuffleCommand [get]
Definition at line 224 of file PlayerViewModel.cs.
{ get; }
SliderValue
double MusicApp.ViewModels.PlayerViewModel.SliderValue [get], [set]
Gets or sets the value of the slider that tracks song playback.
Definition at line 172 of file PlayerViewModel.cs.
        {
            get => _sliderValue;
            set => SetProperty(ref _sliderValue, value);
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.MediaPlayer_Playing(), MusicApp.ViewModels.PlayerViewModel.Timer_Tick(), MusicApp.ViewModels.PlayerViewModel.TrackBarSeek_PreviewMouseLeftButtonUp(), and MusicApp.ViewModels.PlayerViewModel.TrackBarSeek_ValueChanged().
Songs
ObservableCollection<MySong> MusicApp.ViewModels.PlayerViewModel.Songs [get], [set]
Gets or sets the collection of songs currently loaded in the player.
Definition at line 75 of file PlayerViewModel.cs.
        {
            get => _songs;
            set
            {
                SetProperty(ref _songs, value);
                GC.Collect();
            }
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.AddSongToPlaylist(), MusicApp.ViewModels.PlayerViewModel.ExecuteNext(), MusicApp.ViewModels.PlayerViewModel.ExecuteShuffleSongs(), MusicApp.ViewModels.PlayerViewModel.PlayerViewModel(), MusicApp.ViewModels.PlayerViewModel.ProvidePlayerInfo(), and MusicApp.ViewModels.PlayerViewModel.RemoveSongFromPlaylist().
TotalTime
double MusicApp.ViewModels.PlayerViewModel.TotalTime [get], [set]
Gets or sets the total duration of the current song in seconds.
Definition at line 148 of file PlayerViewModel.cs.
        {
            get => _totalTime;
            set
            {
                if (SetProperty(ref _totalTime, value))
                {
                    FormattedTotalTime = TimeSpan.FromSeconds(_totalTime).ToString(@"mm\:ss");
                }
            }
        }
Referenced by MusicApp.ViewModels.PlayerViewModel.MediaPlayer_Playing().
The documentation for this class was generated from the following file:
ViewModels/PlayerViewModel.cs