MusicApp.ViewModels.MainViewModel Class Reference
ViewModel for the main application window, responsible for managing the navigation between different views, handling YouTube service initialization, and managing the application's state.
Public Types
enum MusicSource { None
, Playlist
, Search
, Popular
 }
Represents the different music sources the application can play from.
Public Member Functions
MainViewModel (MainWindow mv)
Initializes a new instance of the MainViewModel class.
void ResetIndices ()
Resets the selected indices for all view models.
void SwitchToHomeView ()
Switches the current view to the HomeView.
void SwitchToSearchView ()
Switches the current view to the SearchView.
void SwitchToPlayerView ()
Switches the current view to the PlayerView.
async Task SearchAndNavigateAsync (string query)
Executes a search and navigates to the SearchView asynchronously.
void NavigateBack ()
Navigates back to the previous view in the history stack.
Public Member Functions inherited from MusicApp.ViewModels.BaseViewModel
void SetPreviousViewModel (BaseViewModel previousViewModel)
Sets the previous ViewModel for navigation purposes.
BaseViewModel GetPreviousViewModel ()
Gets the previous ViewModel for navigation purposes.
Properties
MainWindow MainWindow [get, private set]
SongDatabase? SongDatabase [get, private set]
MyYouTubeService MyYouTubeService [get, private set]
Stack< BaseViewModel > HistoryStack = new Stack<BaseViewModel>() [get, set]
HomeViewModel HomeViewModel [get, private set]
SearchViewModel SearchViewModel [get, private set]
PlayerViewModel PlayerViewModel [get, private set]
MusicSource CurrentMusicSource = MusicSource.None [get, set]
BaseViewModel CurrentViewModel [get, set]
Gets or sets the current view model, updating the mini player visibility and storing the view in history.
bool IsMiniPlayerVisible [get, set]
Gets or sets a value indicating whether the mini player is visible.
Private Member Functions
void InitializeDB ()
Initializes the local database for storing song information.
async void InitializeAsync ()
Initializes the YouTube service and view models asynchronously.
Private Attributes
BaseViewModel _currentViewModel
bool _isMiniPlayerVisible
Additional Inherited Members
Protected Member Functions inherited from MusicApp.ViewModels.BaseViewModel
void OnPropertyChanged ([CallerMemberName] string propertyName=null)
Raises the PropertyChanged event to notify the UI of a property value change.
bool SetProperty< T > (ref T field, T value, [CallerMemberName] string propertyName=null)
Sets the specified property if the value is different, and raises the PropertyChanged event.
Events inherited from MusicApp.ViewModels.BaseViewModel
PropertyChangedEventHandler PropertyChanged
Occurs when a property value changes.
Detailed Description
ViewModel for the main application window, responsible for managing the navigation between different views, handling YouTube service initialization, and managing the application's state.
Definition at line 13 of file MainViewModel.cs.
Member Enumeration Documentation
MusicSource
enum MusicApp.ViewModels.MainViewModel.MusicSource
Represents the different music sources the application can play from.
Definition at line 29 of file MainViewModel.cs.
        {
            None,
            Playlist,
            Search,
            Popular
        }
Constructor & Destructor Documentation
MainViewModel()
MusicApp.ViewModels.MainViewModel.MainViewModel (MainWindow mv) [inline]
Initializes a new instance of the MainViewModel class.
Parameters
mv The main window instance.
Definition at line 64 of file MainViewModel.cs.
        {
            InitializeAsync();
            MainWindow = mv;
        }
References MusicApp.ViewModels.MainViewModel.InitializeAsync().
Member Function Documentation
InitializeAsync()
async void MusicApp.ViewModels.MainViewModel.InitializeAsync () [inline], [private]
Initializes the YouTube service and view models asynchronously.
Definition at line 93 of file MainViewModel.cs.
        {
            InitializeDB();
            MyYouTubeService = await MyYouTubeService.CreateYoutubeServiceAsync();
            HomeViewModel = new HomeViewModel(this);
            SearchViewModel = new SearchViewModel(this, MyYouTubeService);
            PlayerViewModel = new PlayerViewModel(this, MyYouTubeService);
            CurrentViewModel = HomeViewModel;
        }
References MusicApp.Models.MyYouTubeService.CreateYoutubeServiceAsync(), MusicApp.ViewModels.MainViewModel.CurrentViewModel, and MusicApp.ViewModels.MainViewModel.InitializeDB().
Referenced by MusicApp.ViewModels.MainViewModel.MainViewModel().
InitializeDB()
void MusicApp.ViewModels.MainViewModel.InitializeDB () [inline], [private]
Initializes the local database for storing song information.
Definition at line 83 of file MainViewModel.cs.
        {
            string databasePath = "songs.db";
            SongDatabase = new SongDatabase(databasePath);
        }
Referenced by MusicApp.ViewModels.MainViewModel.InitializeAsync().
NavigateBack()
void MusicApp.ViewModels.MainViewModel.NavigateBack () [inline]
Navigates back to the previous view in the history stack.
Definition at line 141 of file MainViewModel.cs.
        {
            if (HistoryStack.Count > 0)
            {
                HistoryStack.Pop();
                BaseViewModel destination = HistoryStack.Pop();
                if (destination is SearchViewModel)
                {
                    SwitchToSearchView();
                }
                else if (destination is PlayerViewModel)
                {
                    SwitchToPlayerView();
                }
                else
                {
                    SwitchToHomeView();
                }
            }
        }
References MusicApp.ViewModels.MainViewModel.SwitchToHomeView(), MusicApp.ViewModels.MainViewModel.SwitchToPlayerView(), and MusicApp.ViewModels.MainViewModel.SwitchToSearchView().
ResetIndices()
void MusicApp.ViewModels.MainViewModel.ResetIndices () [inline]
Resets the selected indices for all view models.
Definition at line 73 of file MainViewModel.cs.
        {
            HomeViewModel.ResetIndices();
            SearchViewModel.ResetIndices();
            PlayerViewModel.ResetIndices();
        }
References MusicApp.ViewModels.HomeViewModel.ResetIndices(), MusicApp.ViewModels.PlayerViewModel.ResetIndices(), and MusicApp.ViewModels.SearchViewModel.ResetIndices().
SearchAndNavigateAsync()
async Task MusicApp.ViewModels.MainViewModel.SearchAndNavigateAsync (string query) [inline]
Executes a search and navigates to the SearchView asynchronously.
Parameters
query The search query string.
Definition at line 132 of file MainViewModel.cs.
        {
            await SearchViewModel.ExecuteSearch(query);
            SwitchToSearchView();
        }
References MusicApp.ViewModels.SearchViewModel.ExecuteSearch(), and MusicApp.ViewModels.MainViewModel.SwitchToSearchView().
SwitchToHomeView()
void MusicApp.ViewModels.MainViewModel.SwitchToHomeView () [inline]
Switches the current view to the HomeView.
Definition at line 107 of file MainViewModel.cs.
        {
            CurrentViewModel = HomeViewModel;
        }
References MusicApp.ViewModels.MainViewModel.CurrentViewModel.
Referenced by MusicApp.ViewModels.MainViewModel.NavigateBack().
SwitchToPlayerView()
void MusicApp.ViewModels.MainViewModel.SwitchToPlayerView () [inline]
Switches the current view to the PlayerView.
Definition at line 123 of file MainViewModel.cs.
        {
            CurrentViewModel = PlayerViewModel;
        }
References MusicApp.ViewModels.MainViewModel.CurrentViewModel.
Referenced by MusicApp.ViewModels.MainViewModel.NavigateBack().
SwitchToSearchView()
void MusicApp.ViewModels.MainViewModel.SwitchToSearchView () [inline]
Switches the current view to the SearchView.
Definition at line 115 of file MainViewModel.cs.
        {
            CurrentViewModel = SearchViewModel;
        }
References MusicApp.ViewModels.MainViewModel.CurrentViewModel.
Referenced by MusicApp.ViewModels.MainViewModel.NavigateBack(), and MusicApp.ViewModels.MainViewModel.SearchAndNavigateAsync().
Member Data Documentation
_currentViewModel
BaseViewModel MusicApp.ViewModels.MainViewModel._currentViewModel [private]
Definition at line 19 of file MainViewModel.cs.
_isMiniPlayerVisible
bool MusicApp.ViewModels.MainViewModel._isMiniPlayerVisible [private]
Definition at line 20 of file MainViewModel.cs.
Property Documentation
CurrentMusicSource
MusicSource MusicApp.ViewModels.MainViewModel.CurrentMusicSource = MusicSource.None [get], [set]
Definition at line 24 of file MainViewModel.cs.
{ get; set; } = MusicSource.None;
CurrentViewModel
BaseViewModel MusicApp.ViewModels.MainViewModel.CurrentViewModel [get], [set]
Gets or sets the current view model, updating the mini player visibility and storing the view in history.
Definition at line 40 of file MainViewModel.cs.
        {
            get => _currentViewModel;
            set
            {
                SetProperty(ref _currentViewModel, value);
                IsMiniPlayerVisible = _currentViewModel != PlayerViewModel && PlayerViewModel.SelectedSongIndex != -1;
                HistoryStack.Push(value);
            }
        }
Referenced by MusicApp.ViewModels.MainViewModel.InitializeAsync(), MusicApp.ViewModels.MainViewModel.SwitchToHomeView(), MusicApp.ViewModels.MainViewModel.SwitchToPlayerView(), and MusicApp.ViewModels.MainViewModel.SwitchToSearchView().
HistoryStack
Stack<BaseViewModel> MusicApp.ViewModels.MainViewModel.HistoryStack = new Stack<BaseViewModel>() [get], [set]
Definition at line 18 of file MainViewModel.cs.
{ get; set; } = new Stack<BaseViewModel>();
HomeViewModel
HomeViewModel MusicApp.ViewModels.MainViewModel.HomeViewModel [get], [private set]
Definition at line 21 of file MainViewModel.cs.
{ get; private set; }
IsMiniPlayerVisible
bool MusicApp.ViewModels.MainViewModel.IsMiniPlayerVisible [get], [set]
Gets or sets a value indicating whether the mini player is visible.
Definition at line 54 of file MainViewModel.cs.
        {
            get => _isMiniPlayerVisible;
            set => SetProperty(ref _isMiniPlayerVisible, value);
        }
MainWindow
MainWindow MusicApp.ViewModels.MainViewModel.MainWindow [get], [private set]
Definition at line 15 of file MainViewModel.cs.
{ get; private set; }
MyYouTubeService
MyYouTubeService MusicApp.ViewModels.MainViewModel.MyYouTubeService [get], [private set]
Definition at line 17 of file MainViewModel.cs.
{ get; private set; }
PlayerViewModel
PlayerViewModel MusicApp.ViewModels.MainViewModel.PlayerViewModel [get], [private set]
Definition at line 23 of file MainViewModel.cs.
{ get; private set; }
SearchViewModel
SearchViewModel MusicApp.ViewModels.MainViewModel.SearchViewModel [get], [private set]
Definition at line 22 of file MainViewModel.cs.
{ get; private set; }
SongDatabase
SongDatabase? MusicApp.ViewModels.MainViewModel.SongDatabase [get], [private set]
Definition at line 16 of file MainViewModel.cs.
{ get; private set; }
The documentation for this class was generated from the following file:
ViewModels/MainViewModel.cs