MusicApp.Models.MySong Class Reference
Represents a song with various details such as name, artist, duration, and thumbnail.
Public Member Functions
async Task< string?> GetPlaylistIdAsync ()
Asynchronously retrieves the playlist ID associated with the song, if available.
Static Public Member Functions
static MySong Create (SongVideoInfo songVideoInfo)
Creates a new MySong instance from a SongVideoInfo object.
static ? MySong Create (CommunityPlaylistSongInfo communityPlaylistSongInfo)
Creates a new MySong instance from a CommunityPlaylistSongInfo object.
static MySong Create (Song song)
Creates a new MySong instance from a Song object.
Properties
string Name [get]
Gets the name of the song.
string? Id [get]
Gets the unique identifier of the song.
string ArtistAndSongName [get]
Gets a formatted string containing the artist(s) and the song name.
ShelfItem[] Artists [get]
Gets an array of ShelfItem representing the artists of the song.
string ArtistsString [get]
Gets a string representing the names of the artists, joined by commas.
TimeSpan Duration [get]
Gets the duration of the song.
string? Thumbnail [get, private set]
Gets the URL of the song's thumbnail.
string? _playlistId = null [get]
Private Member Functions
MySong (Song song)
Initializes a new instance of the MySong class based on a Song object.
MySong (string name, string? id, ShelfItem[] artists, TimeSpan duration, string? thumbnail, string? playlistId=null)
Initializes a new instance of the MySong class with specified parameters.
string GetArtistAndSongNameString ()
Generates a formatted string representing the artist(s) and song name.
Detailed Description
Represents a song with various details such as name, artist, duration, and thumbnail.
Definition at line 17 of file MySong.cs.
Constructor & Destructor Documentation
MySong() [1/2]
MusicApp.Models.MySong.MySong (Song song) [inline], [private]
Initializes a new instance of the MySong class based on a Song object.
Parameters
song The Song object to initialize from.
Definition at line 76 of file MySong.cs.
        {
            Name = song.Name;
            Id = song.Id;
            Artists = song.Artists;
            _playlistId = song.Radio.PlaylistId;
            Duration = song.Duration;
            Thumbnail = song.Thumbnails.LastOrDefault()?.Url;
            ArtistAndSongName = GetArtistAndSongNameString();
        }
References MusicApp.Models.MySong.ArtistAndSongName, MusicApp.Models.MySong.Artists, MusicApp.Models.MySong.Duration, MusicApp.Models.MySong.GetArtistAndSongNameString(), MusicApp.Models.MySong.Id, MusicApp.Models.MySong.Name, and MusicApp.Models.MySong.Thumbnail.
Referenced by MusicApp.Models.MySong.Create(), MusicApp.Models.MySong.Create(), and MusicApp.Models.MySong.Create().
MySong() [2/2]
MusicApp.Models.MySong.MySong (string name, string? id, ShelfItem[] artists, TimeSpan duration, string? thumbnail, string? playlistId = null) [inline], [private]
Initializes a new instance of the MySong class with specified parameters.
Parameters
name The name of the song.
id The unique identifier of the song.
artists An array of ShelfItem representing the artists of the song.
duration The duration of the song.
thumbnail The URL of the song's thumbnail.
playlistId The playlist ID associated with the song, if available.
Definition at line 96 of file MySong.cs.
        {
            Name = name;
            Id = id;
            Artists = artists;
            _playlistId = playlistId;
            Duration = duration;
            Thumbnail = thumbnail;
            ArtistAndSongName = GetArtistAndSongNameString();
        }
References MusicApp.Models.MySong.ArtistAndSongName, MusicApp.Models.MySong.Artists, MusicApp.Models.MySong.Duration, MusicApp.Models.MySong.GetArtistAndSongNameString(), MusicApp.Models.MySong.Id, MusicApp.Models.MySong.Name, and MusicApp.Models.MySong.Thumbnail.
Member Function Documentation
Create() [1/3]
static ? MySong MusicApp.Models.MySong.Create (CommunityPlaylistSongInfo communityPlaylistSongInfo) [inline], [static]
Creates a new MySong instance from a CommunityPlaylistSongInfo object.
Parameters
communityPlaylistSongInfo The CommunityPlaylistSongInfo object to create from.
Returns
A new instance of MySong, or null if the input is null.
Definition at line 124 of file MySong.cs.
        {
            if (communityPlaylistSongInfo == null)
            {
                return null;
            }
            MySong mySong = new MySong(communityPlaylistSongInfo.Name, communityPlaylistSongInfo.Id, communityPlaylistSongInfo.Artists, communityPlaylistSongInfo.Duration, communityPlaylistSongInfo.Thumbnails.LastOrDefault()?.Url);
            return mySong;
        }
References MusicApp.Models.MySong.MySong().
Create() [2/3]
static MySong MusicApp.Models.MySong.Create (Song song) [inline], [static]
Creates a new MySong instance from a Song object.
Parameters
song The Song object to create from.
Returns
A new instance of MySong.
Definition at line 140 of file MySong.cs.
        {
            var mySong = new MySong(song);
            return mySong;
        }
References MusicApp.Models.MySong.MySong().
Create() [3/3]
static MySong MusicApp.Models.MySong.Create (SongVideoInfo songVideoInfo) [inline], [static]
Creates a new MySong instance from a SongVideoInfo object.
Parameters
songVideoInfo The SongVideoInfo object to create from.
Returns
A new instance of MySong.
Definition at line 112 of file MySong.cs.
        {
            MySong mySong = new MySong(songVideoInfo.Name, songVideoInfo.Id, songVideoInfo.Artists, songVideoInfo.Duration, songVideoInfo.Thumbnails.LastOrDefault()?.Url);
            return mySong;
        }
References MusicApp.Models.MySong.MySong().
Referenced by MusicApp.Models.MyYouTubeService.ConvertSongsToMySongsShelf(), MusicApp.Models.MyYouTubeService.FetchPlaylistContentAsync(), MusicApp.Models.MyYouTubeService.FetchRadioSongsAsync(), MusicApp.Models.MyYouTubeService.FetchSongAsync(), MusicApp.Models.MyYouTubeService.FetchSongsAsync(), MusicApp.Models.MyYouTubeService.FetchSongShelvesAsync(), and MusicApp.Views.HomeView.GetRandomSongs().
GetArtistAndSongNameString()
string MusicApp.Models.MySong.GetArtistAndSongNameString () [inline], [private]
Generates a formatted string representing the artist(s) and song name.
Returns
A string in the format "Artist(s) - Song Name".
Definition at line 151 of file MySong.cs.
        {
            return $" {string.Join(", ", Artists.Select(artist => artist.Name))} - {Name}";
        }
Referenced by MusicApp.Models.MySong.MySong(), and MusicApp.Models.MySong.MySong().
GetPlaylistIdAsync()
async Task< string?> MusicApp.Models.MySong.GetPlaylistIdAsync () [inline]
Asynchronously retrieves the playlist ID associated with the song, if available.
Returns
The playlist ID as a string, or null if not available.
Definition at line 60 of file MySong.cs.
        {
            if (_playlistId != null)
            {
                return _playlistId;
            }
            var song = await MyYouTubeService.FetchSongAsync(ArtistAndSongName);
            return song?._playlistId;
        }
References MusicApp.Models.MySong.ArtistAndSongName, and MusicApp.Models.MyYouTubeService.FetchSongAsync().
Property Documentation
_playlistId
string? MusicApp.Models.MySong._playlistId = null [get], [private]
Definition at line 54 of file MySong.cs.
{ get; } = null;
ArtistAndSongName
string MusicApp.Models.MySong.ArtistAndSongName [get]
Gets a formatted string containing the artist(s) and the song name.
Definition at line 32 of file MySong.cs.
{ get; }
Referenced by MusicApp.Models.MySong.GetPlaylistIdAsync(), MusicApp.Models.MySong.MySong(), and MusicApp.Models.MySong.MySong().
Artists
ShelfItem [] MusicApp.Models.MySong.Artists [get]
Gets an array of ShelfItem representing the artists of the song.
Definition at line 37 of file MySong.cs.
{ get; }
Referenced by MusicApp.Models.MySong.MySong(), MusicApp.Models.MySong.MySong(), and MusicApp.ViewModels.PlayerViewModel.PlaySelectedSong().
ArtistsString
string MusicApp.Models.MySong.ArtistsString [get]
Gets a string representing the names of the artists, joined by commas.
Definition at line 42 of file MySong.cs.
Duration
TimeSpan MusicApp.Models.MySong.Duration [get]
Gets the duration of the song.
Definition at line 47 of file MySong.cs.
{ get; }
Referenced by MusicApp.Models.MySong.MySong(), and MusicApp.Models.MySong.MySong().
Id
string? MusicApp.Models.MySong.Id [get]
Gets the unique identifier of the song.
Definition at line 27 of file MySong.cs.
{ get; }
Referenced by MusicApp.ViewModels.PlayerViewModel.DisplayPicture(), MusicApp.Models.MySong.MySong(), MusicApp.Models.MySong.MySong(), MusicApp.ViewModels.PlayerViewModel.PlaySelectedSong(), and MusicApp.Models.MyYouTubeService.RemoveSongFromPlaylist().
Name
string MusicApp.Models.MySong.Name [get]
Gets the name of the song.
Definition at line 22 of file MySong.cs.
{ get; }
Referenced by MusicApp.Models.MySong.MySong(), MusicApp.Models.MySong.MySong(), and MusicApp.ViewModels.PlayerViewModel.PlaySelectedSong().
Thumbnail
string? MusicApp.Models.MySong.Thumbnail [get], [private set]
Gets the URL of the song's thumbnail.
Definition at line 52 of file MySong.cs.
{ get; private set; }
Referenced by MusicApp.Models.MySong.MySong(), and MusicApp.Models.MySong.MySong().
The documentation for this class was generated from the following file:
Models/MySong.cs