ThumbnailHelper Class Reference
Static Public Member Functions
static async Task< BitmapImage > GetHighQualityThumbnailAsync (string songId)
Asynchronously retrieves the high-quality thumbnail for a given song ID. If the high-quality thumbnail is not available, it attempts to retrieve the medium-quality thumbnail. If neither are available, it falls back to a low-quality thumbnail.
static async Task< BitmapImage > GetMediumQualityThumbnailAsync (string songId)
Asynchronously retrieves the medium-quality thumbnail for a given song ID.
static async Task< BitmapImage > GetLowQualityThumbnailAsync (string songId)
Asynchronously retrieves the low-quality thumbnail for a given song ID.
static async Task< BitmapImage > GetSquareThumbnailAsync (string videoUrl)
Asynchronously retrieves and crops a thumbnail to a square aspect ratio.
Static Private Member Functions
static BitmapImage BitmapToBitmapImage (Bitmap bitmap)
Converts a Bitmap to a BitmapImage.
Detailed Description
Definition at line 8 of file ThumbnailHelper.cs.
Member Function Documentation
BitmapToBitmapImage()
static BitmapImage ThumbnailHelper.BitmapToBitmapImage (Bitmap bitmap) [inline], [static], [private]
Converts a Bitmap to a BitmapImage.
Parameters
bitmap The bitmap to convert.
Returns
A BitmapImage created from the bitmap.
Definition at line 101 of file ThumbnailHelper.cs.
    {
        using (MemoryStream memory = new MemoryStream())
        {
            bitmap.Save(memory, System.Drawing.Imaging.ImageFormat.Png);
            memory.Position = 0;
            BitmapImage bitmapImage = new BitmapImage();
            bitmapImage.BeginInit();
            bitmapImage.StreamSource = memory;
            bitmapImage.CacheOption = BitmapCacheOption.OnLoad;
            bitmapImage.EndInit();
            bitmapImage.Freeze();
            return bitmapImage;
        }
    }
Referenced by GetSquareThumbnailAsync().
GetHighQualityThumbnailAsync()
static async Task< BitmapImage > ThumbnailHelper.GetHighQualityThumbnailAsync (string songId) [inline], [static]
Asynchronously retrieves the high-quality thumbnail for a given song ID. If the high-quality thumbnail is not available, it attempts to retrieve the medium-quality thumbnail. If neither are available, it falls back to a low-quality thumbnail.
Parameters
songId The ID of the song to retrieve the thumbnail for.
Returns
A BitmapImage containing the thumbnail image.
Definition at line 17 of file ThumbnailHelper.cs.
    {
        try
        {
            var imageUrl = $"https://img.youtube.com/vi/{songId}/maxresdefault.jpg";
            return await GetSquareThumbnailAsync(imageUrl);
        }
        catch (Exception)
        {
            try
            {
                return await GetMediumQualityThumbnailAsync(songId);
            }
            catch (Exception)
            {
                var imageUrl = $"https://img.youtube.com/vi/{songId}/0.jpg";
                return await GetSquareThumbnailAsync(imageUrl);
            }
        }
    }
References GetMediumQualityThumbnailAsync(), and GetSquareThumbnailAsync().
Referenced by MusicApp.ViewModels.PlayerViewModel.DisplayPicture().
GetLowQualityThumbnailAsync()
static async Task< BitmapImage > ThumbnailHelper.GetLowQualityThumbnailAsync (string songId) [inline], [static]
Asynchronously retrieves the low-quality thumbnail for a given song ID.
Parameters
songId The ID of the song to retrieve the thumbnail for.
Returns
A BitmapImage containing the thumbnail image.
Definition at line 57 of file ThumbnailHelper.cs.
    {
        var imageUrl = $"https://img.youtube.com/vi/{songId}/1.jpg";
        return await GetSquareThumbnailAsync(imageUrl);
    }
References GetSquareThumbnailAsync().
GetMediumQualityThumbnailAsync()
static async Task< BitmapImage > ThumbnailHelper.GetMediumQualityThumbnailAsync (string songId) [inline], [static]
Asynchronously retrieves the medium-quality thumbnail for a given song ID.
Parameters
songId The ID of the song to retrieve the thumbnail for.
Returns
A BitmapImage containing the thumbnail image.
Definition at line 45 of file ThumbnailHelper.cs.
    {
        var imageUrl = $"https://img.youtube.com/vi/{songId}/sd1.jpg";
        return await GetSquareThumbnailAsync(imageUrl);
    }
References GetSquareThumbnailAsync().
Referenced by GetHighQualityThumbnailAsync().
GetSquareThumbnailAsync()
static async Task< BitmapImage > ThumbnailHelper.GetSquareThumbnailAsync (string videoUrl) [inline], [static]
Asynchronously retrieves and crops a thumbnail to a square aspect ratio.
Parameters
videoUrl The URL of the video thumbnail to retrieve.
Returns
A BitmapImage containing the square-cropped thumbnail image.
Definition at line 69 of file ThumbnailHelper.cs.
    {
        using (HttpClient client = new HttpClient())
        {
            var response = await client.GetAsync(videoUrl);
            response.EnsureSuccessStatusCode();
            var stream = await response.Content.ReadAsStreamAsync();
            using (var originalImage = new Bitmap(stream))
            {
                int size = Math.Min(originalImage.Width, originalImage.Height);
                int x = (originalImage.Width - size) / 2;
                int y = (originalImage.Height - size) / 2;
                using (var croppedImage = new Bitmap(size, size))
                {
                    using (Graphics g = Graphics.FromImage(croppedImage))
                    {
                        g.DrawImage(originalImage, new Rectangle(0, 0, size, size), x, y, size, size, GraphicsUnit.Pixel);
                    }
                    return BitmapToBitmapImage(croppedImage);
                }
            }
        }
    }
References BitmapToBitmapImage().
Referenced by GetHighQualityThumbnailAsync(), GetLowQualityThumbnailAsync(), and GetMediumQualityThumbnailAsync().
The documentation for this class was generated from the following file:
Models/ThumbnailHelper.cs