MusicApp.ViewModels.SearchViewModel Class Reference
ViewModel for handling song search functionality, interacting with the YouTube Music API, and managing search results.
Public Member Functions
void ResetIndices ()
Resets the selected song index to its default value (-1).
SearchViewModel (MainViewModel mainViewModel, MyYouTubeService ys)
Initializes a new instance of the SearchViewModel class.
async Task ExecuteSearch (string query)
Executes the search using the YouTube Music API and updates the song collection.
Public Member Functions inherited from MusicApp.ViewModels.BaseViewModel
void SetPreviousViewModel (BaseViewModel previousViewModel)
Sets the previous ViewModel for navigation purposes.
BaseViewModel GetPreviousViewModel ()
Gets the previous ViewModel for navigation purposes.
Properties
MyShelf< MySong > Songs [get, set]
Gets or sets the collection of songs returned by the search query.
int SelectedSongIndex [set]
Gets or sets the index of the currently selected song in the search results.
string SearchQuery [get, set]
Gets or sets the search query entered by the user.
ICommand SearchCommand [get]
Command for executing the search based on the search query.
ICommand BackCommand [get]
Command for navigating back to the previous view.
Private Member Functions
async void HandleSelectedSongIndex (int index)
Handles the selection of a song, fetching related songs and updating the player view.
void ExecuteBack (object parameter)
Navigates back to the previous view, clearing the continuation token.
Private Attributes
readonly MainViewModel _mainViewModel
readonly MyYouTubeService _youTubeService
MyShelf< MySong > _songs
string _searchQuery = string.Empty
int _selectedSongIndex = -1
string? _searchContinuationToken
Additional Inherited Members
Protected Member Functions inherited from MusicApp.ViewModels.BaseViewModel
void OnPropertyChanged ([CallerMemberName] string propertyName=null)
Raises the PropertyChanged event to notify the UI of a property value change.
bool SetProperty< T > (ref T field, T value, [CallerMemberName] string propertyName=null)
Sets the specified property if the value is different, and raises the PropertyChanged event.
Events inherited from MusicApp.ViewModels.BaseViewModel
PropertyChangedEventHandler PropertyChanged
Occurs when a property value changes.
Detailed Description
ViewModel for handling song search functionality, interacting with the YouTube Music API, and managing search results.
Definition at line 19 of file SearchViewModel.cs.
Constructor & Destructor Documentation
SearchViewModel()
MusicApp.ViewModels.SearchViewModel.SearchViewModel (MainViewModel mainViewModel, MyYouTubeService ys) [inline]
Initializes a new instance of the SearchViewModel class.
Parameters
mainViewModel The main view model controlling the application's state.
ys The YouTube service for interacting with the YouTube Music API.
Definition at line 117 of file SearchViewModel.cs.
        {
            _mainViewModel = mainViewModel;
            _youTubeService = ys;
            _songs = new MyShelf<MySong>(new(), null);
            SearchCommand = new RelayCommand(async _ => await ExecuteSearch(_searchQuery));
            BackCommand = new RelayCommand(ExecuteBack);
        }
References MusicApp.ViewModels.SearchViewModel.BackCommand, MusicApp.ViewModels.SearchViewModel.ExecuteBack(), MusicApp.ViewModels.SearchViewModel.ExecuteSearch(), and MusicApp.ViewModels.SearchViewModel.SearchCommand.
Member Function Documentation
ExecuteBack()
void MusicApp.ViewModels.SearchViewModel.ExecuteBack (object parameter) [inline], [private]
Navigates back to the previous view, clearing the continuation token.
Parameters
parameter Optional parameter for the command.
Definition at line 168 of file SearchViewModel.cs.
        {
            _searchContinuationToken = null;
            _mainViewModel.NavigateBack();
        }
Referenced by MusicApp.ViewModels.SearchViewModel.SearchViewModel().
ExecuteSearch()
async Task MusicApp.ViewModels.SearchViewModel.ExecuteSearch (string query) [inline]
Executes the search using the YouTube Music API and updates the song collection.
Parameters
query The search query entered by the user.
Returns
A task representing the asynchronous operation.
Definition at line 132 of file SearchViewModel.cs.
        {
            if (string.IsNullOrWhiteSpace(query))
            {
                MessageBox.Show("Please enter a search query.");
                return;
            }
            try
            {
                var shelf = await _youTubeService.FetchSongShelvesAsync(query, _searchContinuationToken);
                if (shelf == null)
                {
                    MessageBox.Show("No songs found.");
                    return;
                }
                Songs = shelf;
                _searchContinuationToken = shelf.ContinuationToken;
                if (!shelf.Items.Any())
                {
                    MessageBox.Show("No songs found.");
                    return;
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"An error occurred: {ex.Message}");
            }
        }
References MusicApp.Models.MyShelf< T >.ContinuationToken, and MusicApp.ViewModels.SearchViewModel.Songs.
Referenced by MusicApp.ViewModels.MainViewModel.SearchAndNavigateAsync(), and MusicApp.ViewModels.SearchViewModel.SearchViewModel().
HandleSelectedSongIndex()
async void MusicApp.ViewModels.SearchViewModel.HandleSelectedSongIndex (int index) [inline], [private]
Handles the selection of a song, fetching related songs and updating the player view.
Parameters
index The index of the selected song.
Definition at line 63 of file SearchViewModel.cs.
        {
            if (Songs.Items.ElementAtOrDefault(index) is MySong song and not null)
            {
                var newSongs = new MyShelf<MySong>(new ObservableCollection<MySong>() { song }, null);
                var radioPlaylistId = await song.GetPlaylistIdAsync();
                var radioSongs = await _mainViewModel.MyYouTubeService.FetchRadioSongsAsync(radioPlaylistId);
                _mainViewModel.ResetIndices();
                _mainViewModel.CurrentMusicSource = MainViewModel.MusicSource.Search;
                if (radioSongs == null)
                {
                    MessageBox.Show("No songs found.");
                    return;
                }
                foreach (var item in radioSongs)
                {
                    newSongs.Items.Add(item);
                }
                _mainViewModel.PlayerViewModel.ProvidePlayerInfo(newSongs.Items, 0, GetInfoString("Queue"));
                _mainViewModel.SwitchToPlayerView();
            }
        }
References MusicApp.Models.MyShelf< T >.Items, and MusicApp.ViewModels.SearchViewModel.Songs.
ResetIndices()
void MusicApp.ViewModels.SearchViewModel.ResetIndices () [inline]
Resets the selected song index to its default value (-1).
Definition at line 31 of file SearchViewModel.cs.
        {
            SelectedSongIndex = -1;
        }
References MusicApp.ViewModels.SearchViewModel.SelectedSongIndex.
Referenced by MusicApp.ViewModels.MainViewModel.ResetIndices().
Member Data Documentation
_mainViewModel
readonly MainViewModel MusicApp.ViewModels.SearchViewModel._mainViewModel [private]
Definition at line 21 of file SearchViewModel.cs.
_searchContinuationToken
string? MusicApp.ViewModels.SearchViewModel._searchContinuationToken [private]
Definition at line 26 of file SearchViewModel.cs.
_searchQuery
string MusicApp.ViewModels.SearchViewModel._searchQuery = string.Empty [private]
Definition at line 24 of file SearchViewModel.cs.
_selectedSongIndex
int MusicApp.ViewModels.SearchViewModel._selectedSongIndex = -1 [private]
Definition at line 25 of file SearchViewModel.cs.
_songs
MyShelf<MySong> MusicApp.ViewModels.SearchViewModel._songs [private]
Definition at line 23 of file SearchViewModel.cs.
_youTubeService
readonly MyYouTubeService MusicApp.ViewModels.SearchViewModel._youTubeService [private]
Definition at line 22 of file SearchViewModel.cs.
Property Documentation
BackCommand
ICommand MusicApp.ViewModels.SearchViewModel.BackCommand [get]
Command for navigating back to the previous view.
Definition at line 110 of file SearchViewModel.cs.
{ get; }
Referenced by MusicApp.ViewModels.SearchViewModel.SearchViewModel().
SearchCommand
ICommand MusicApp.ViewModels.SearchViewModel.SearchCommand [get]
Command for executing the search based on the search query.
Definition at line 105 of file SearchViewModel.cs.
{ get; }
Referenced by MusicApp.ViewModels.SearchViewModel.SearchViewModel(), and MusicApp.Views.SearchView.TextBox_KeyDown().
SearchQuery
string MusicApp.ViewModels.SearchViewModel.SearchQuery [get], [set]
Gets or sets the search query entered by the user.
Definition at line 92 of file SearchViewModel.cs.
        {
            get => _searchQuery;
            set
            {
                SetProperty(ref _searchQuery, value);
                _searchContinuationToken = null;
            }
        }
SelectedSongIndex
int MusicApp.ViewModels.SearchViewModel.SelectedSongIndex [set]
Gets or sets the index of the currently selected song in the search results.
Definition at line 48 of file SearchViewModel.cs.
        {
            set
            {
                if (SetProperty(ref _selectedSongIndex, value))
                {
                    HandleSelectedSongIndex(value);
                }
            }
        }
Referenced by MusicApp.ViewModels.SearchViewModel.ResetIndices().
Songs
MyShelf<MySong> MusicApp.ViewModels.SearchViewModel.Songs [get], [set]
Gets or sets the collection of songs returned by the search query.
Definition at line 39 of file SearchViewModel.cs.
        {
            get => _songs;
            set => SetProperty(ref _songs, value);
        }
Referenced by MusicApp.ViewModels.SearchViewModel.ExecuteSearch(), and MusicApp.ViewModels.SearchViewModel.HandleSelectedSongIndex().
The documentation for this class was generated from the following file:
ViewModels/SearchViewModel.cs