MusicApp.Views.HomeView Class Reference
Interaction logic for HomeView.xaml. This class handles the main view logic for displaying and interacting with playlists and songs in the MusicApp.
Public Types
enum ListBoxType { RandomSongsFromAllPlaylists
, SongsFromSpecificAuthor
 }
Private Member Functions
void TextBox_KeyDown (object sender, KeyEventArgs e)
Handles the KeyDown event for the search TextBox, triggering the search command when Enter is pressed.
void ListViewScrollViewer_PreviewMouseWheel (object sender, MouseWheelEventArgs e)
Handles the MouseWheel event for the ListView ScrollViewer to enable smooth scrolling.
void PlaylistListBoxItemCommand (object sender, MouseButtonEventArgs e)
Handles the MouseLeftButtonUp event for selecting a playlist.
async void RadioSongListBoxCommand (object sender, MouseButtonEventArgs e, ObservableCollection< MySong > songs, int index)
Handles the MouseLeftButtonUp event for playing a song from the radio list.
void PopularSongsListBoxCommand (object sender, MouseButtonEventArgs e)
Handles the MouseLeftButtonUp event for playing a popular song.
void ExecuteDeletePlaylistCommand (object sender)
Executes the delete command for a playlist.
void RemovePlaylist_ComboBox (object sender, RoutedEventArgs e)
Handles the Click event for removing a playlist using a context menu.
async void DynamicScrollViewer_ScrollChanged (object sender, ScrollChangedEventArgs e)
Handles the ScrollChanged event for dynamically loading additional content as the user scrolls.
void ListBox_ScrollChanged (object sender, ScrollChangedEventArgs e)
Prevents the ListBox from triggering the main ScrollViewer's event when scrolling.
async Task AddDynamicListBoxSectionAsync ()
Adds a dynamically generated ListBox section to the main panel based on a random selection of ListBoxType.
async Task AddRandomSongsListBoxAsync ()
Adds a ListBox with a random collection of songs from all playlists to the main panel.
async Task AddSongsFromAuthorListBoxAsync ()
Adds a ListBox with songs from a specific author to the main panel.
ListBox CreateListBox (ObservableCollection< MySong > songs)
Creates a ListBox with the specified songs and sets up the necessary event handlers and templates.
DataTemplate CreateDataTemplate ()
Creates a DataTemplate for the items in the dynamically generated ListBoxes.
ContextMenu CreateContextMenu ()
Creates a context menu with an "Add to Playlist" option for each song item.
async Task< ObservableCollection< MySong >?> GetRandomSongs ()
Gets a collection of random songs from the database for recommendation.
string? GetRandomAuthor (IEnumerable< MySong > songs)
Gets a random author from the list of available songs.
void ExecuteAddSongToPlaylist (object sender)
Executes the command to add a song to a playlist from the context menu.
void AddSongToPlaylist_ComboBox (object sender, RoutedEventArgs e)
Handles the Click event for adding a song to a playlist via the context menu.
Private Attributes
bool _isLoadingPanel = false
readonly Random _random = new()
Detailed Description
Interaction logic for HomeView.xaml. This class handles the main view logic for displaying and interacting with playlists and songs in the MusicApp.
Definition at line 20 of file HomeView.xaml.cs.
Member Enumeration Documentation
ListBoxType
enum MusicApp.Views.HomeView.ListBoxType
Definition at line 22 of file HomeView.xaml.cs.
        {
            RandomSongsFromAllPlaylists,
            SongsFromSpecificAuthor
        }
Constructor & Destructor Documentation
HomeView()
MusicApp.Views.HomeView.HomeView () [inline]
Definition at line 31 of file HomeView.xaml.cs.
        {
            InitializeComponent();
        }
Member Function Documentation
AddDynamicListBoxSectionAsync()
async Task MusicApp.Views.HomeView.AddDynamicListBoxSectionAsync () [inline], [private]
Adds a dynamically generated ListBox section to the main panel based on a random selection of ListBoxType.
Definition at line 137 of file HomeView.xaml.cs.
        {
            var selectedType = (ListBoxType)_random.Next(Enum.GetValues(typeof(ListBoxType)).Length);
            switch (selectedType)
            {
                case ListBoxType.RandomSongsFromAllPlaylists:
                    await AddRandomSongsListBoxAsync();
                    break;
                case ListBoxType.SongsFromSpecificAuthor:
                    await AddSongsFromAuthorListBoxAsync();
                    break;
            }
        }
References MusicApp.Views.HomeView.AddRandomSongsListBoxAsync(), and MusicApp.Views.HomeView.AddSongsFromAuthorListBoxAsync().
Referenced by MusicApp.Views.HomeView.DynamicScrollViewer_ScrollChanged().
AddRandomSongsListBoxAsync()
async Task MusicApp.Views.HomeView.AddRandomSongsListBoxAsync () [inline], [private]
Adds a ListBox with a random collection of songs from all playlists to the main panel.
Definition at line 156 of file HomeView.xaml.cs.
        {
            var viewModel = DataContext as HomeViewModel;
            if (viewModel == null || viewModel.AllPlaylistSongs == null || !viewModel.AllPlaylistSongs.Any())
                return;
            var randomSongs = await GetRandomSongs();
            if (randomSongs == null || randomSongs.Count == 0) return;
            var textBlock = new TextBlock
            {
                Text = "Your Favourite Songs",
                FontWeight = FontWeights.Bold,
                FontSize = 24,
                Foreground = new SolidColorBrush(Colors.White),
                Margin = new Thickness(10, 0, 0, 0)
            };
            MainPanel.Children.Add(textBlock);
            var listBox = CreateListBox(randomSongs);
            MainPanel.Children.Add(listBox);
        }
References MusicApp.Views.HomeView.CreateListBox(), and MusicApp.Views.HomeView.GetRandomSongs().
Referenced by MusicApp.Views.HomeView.AddDynamicListBoxSectionAsync().
AddSongsFromAuthorListBoxAsync()
async Task MusicApp.Views.HomeView.AddSongsFromAuthorListBoxAsync () [inline], [private]
Adds a ListBox with songs from a specific author to the main panel.
Definition at line 182 of file HomeView.xaml.cs.
        {
            var viewModel = DataContext as HomeViewModel;
            if (viewModel == null || viewModel.AllPlaylistSongs == null || !viewModel.AllPlaylistSongs.Any())
                return;
            var randomAuthor = GetRandomAuthor(viewModel.AllPlaylistSongs);
            if (randomAuthor == null) return;
            var authorSongs = await MyYouTubeService.FetchSongsAsync(randomAuthor, 10);
            if (authorSongs == null || authorSongs.Count == 0) return;
            var textBlock = new TextBlock
            {
                Text = $"Songs by {randomAuthor}",
                FontWeight = FontWeights.Bold,
                FontSize = 24,
                Foreground = new SolidColorBrush(Colors.White),
                Margin = new Thickness(10, 0, 0, 0)
            };
            MainPanel.Children.Add(textBlock);
            var listBox = CreateListBox(authorSongs);
            MainPanel.Children.Add(listBox);
        }
References MusicApp.Views.HomeView.CreateListBox(), MusicApp.Models.MyYouTubeService.FetchSongsAsync(), and MusicApp.Views.HomeView.GetRandomAuthor().
Referenced by MusicApp.Views.HomeView.AddDynamicListBoxSectionAsync().
AddSongToPlaylist_ComboBox()
void MusicApp.Views.HomeView.AddSongToPlaylist_ComboBox (object sender, RoutedEventArgs e) [inline], [private]
Handles the Click event for adding a song to a playlist via the context menu.
Definition at line 355 of file HomeView.xaml.cs.
        {
            ExecuteAddSongToPlaylist(sender);
        }
References MusicApp.Views.HomeView.ExecuteAddSongToPlaylist().
Referenced by MusicApp.Views.HomeView.CreateContextMenu().
CreateContextMenu()
ContextMenu MusicApp.Views.HomeView.CreateContextMenu () [inline], [private]
Creates a context menu with an "Add to Playlist" option for each song item.
Definition at line 296 of file HomeView.xaml.cs.
        {
            var contextMenu = new ContextMenu();
            var addMenuItem = new MenuItem { Header = "Add to Playlist" };
            addMenuItem.Click += AddSongToPlaylist_ComboBox;
            contextMenu.Items.Add(addMenuItem);
            return contextMenu;
        }
References MusicApp.Views.HomeView.AddSongToPlaylist_ComboBox().
Referenced by MusicApp.Views.HomeView.CreateDataTemplate().
CreateDataTemplate()
DataTemplate MusicApp.Views.HomeView.CreateDataTemplate () [inline], [private]
Creates a DataTemplate for the items in the dynamically generated ListBoxes.
Definition at line 240 of file HomeView.xaml.cs.
        {
            var stackPanelFactory = new FrameworkElementFactory(typeof(StackPanel));
            stackPanelFactory.SetValue(StackPanel.MarginProperty, new Thickness(10));
            stackPanelFactory.SetValue(StackPanel.HorizontalAlignmentProperty, HorizontalAlignment.Center);
            var viewboxFactory = new FrameworkElementFactory(typeof(Viewbox));
            viewboxFactory.SetValue(Viewbox.HorizontalAlignmentProperty, HorizontalAlignment.Center);
            viewboxFactory.SetValue(Viewbox.VerticalAlignmentProperty, VerticalAlignment.Center);
            var borderFactory = new FrameworkElementFactory(typeof(Border));
            borderFactory.SetValue(Border.BackgroundProperty, new SolidColorBrush(Color.FromRgb(51, 51, 51)));
            borderFactory.SetValue(Border.CornerRadiusProperty, new CornerRadius(10));
            borderFactory.SetValue(Border.WidthProperty, 120.0);
            borderFactory.SetValue(Border.HeightProperty, 120.0);
            borderFactory.SetValue(Border.HorizontalAlignmentProperty, HorizontalAlignment.Center);
            var imageFactory = new FrameworkElementFactory(typeof(Image));
            imageFactory.SetBinding(Image.SourceProperty, new Binding("Thumbnail"));
            imageFactory.SetValue(Image.WidthProperty, 120.0);
            imageFactory.SetValue(Image.HeightProperty, 120.0);
            imageFactory.SetValue(Image.StretchProperty, Stretch.UniformToFill);
            var rectangleGeometry = new RectangleGeometry(new Rect(0, 0, 120, 120), 10, 10);
            imageFactory.SetValue(Image.ClipProperty, rectangleGeometry);
            borderFactory.AppendChild(imageFactory);
            viewboxFactory.AppendChild(borderFactory);
            stackPanelFactory.AppendChild(viewboxFactory);
            var textBlockNameFactory = new FrameworkElementFactory(typeof(TextBlock));
            textBlockNameFactory.SetBinding(TextBlock.TextProperty, new Binding("Name"));
            textBlockNameFactory.SetValue(TextBlock.ForegroundProperty, new SolidColorBrush(Colors.White));
            textBlockNameFactory.SetValue(TextBlock.TextAlignmentProperty, TextAlignment.Center);
            textBlockNameFactory.SetValue(TextBlock.WidthProperty, 130.0);
            textBlockNameFactory.SetValue(TextBlock.MarginProperty, new Thickness(5, 10, 5, 0));
            stackPanelFactory.AppendChild(textBlockNameFactory);
            var textBlockArtistsFactory = new FrameworkElementFactory(typeof(TextBlock));
            textBlockArtistsFactory.SetBinding(TextBlock.TextProperty, new Binding("ArtistsString"));
            textBlockArtistsFactory.SetValue(TextBlock.ForegroundProperty, new SolidColorBrush(Colors.White));
            textBlockArtistsFactory.SetValue(TextBlock.TextAlignmentProperty, TextAlignment.Center);
            textBlockArtistsFactory.SetValue(TextBlock.WidthProperty, 130.0);
            textBlockArtistsFactory.SetValue(TextBlock.MarginProperty, new Thickness(5, 10, 5, 0));
            stackPanelFactory.AppendChild(textBlockArtistsFactory);
            var contextMenuSetter = new Setter(ContextMenuService.ContextMenuProperty, CreateContextMenu());
            stackPanelFactory.SetValue(FrameworkElement.ContextMenuProperty, CreateContextMenu());
            var dataTemplate = new DataTemplate { VisualTree = stackPanelFactory };
            return dataTemplate;
        }
References MusicApp.Views.HomeView.CreateContextMenu().
Referenced by MusicApp.Views.HomeView.CreateListBox().
CreateListBox()
ListBox MusicApp.Views.HomeView.CreateListBox (ObservableCollection< MySong > songs) [inline], [private]
Creates a ListBox with the specified songs and sets up the necessary event handlers and templates.
Definition at line 211 of file HomeView.xaml.cs.
        {
            var listBox = new ListBox
            {
                BorderThickness = new Thickness(0),
                Background = new SolidColorBrush(Colors.Transparent),
                SelectedIndex = -1,
                ItemsSource = songs
            };
            listBox.PreviewMouseLeftButtonUp += (s, e) => RadioSongListBoxCommand(s, e, songs, listBox.SelectedIndex);
            listBox.AddHandler(ScrollViewer.ScrollChangedEvent, new ScrollChangedEventHandler(ListBox_ScrollChanged), true);
            var itemsPanelTemplate = new ItemsPanelTemplate
            {
                VisualTree = new FrameworkElementFactory(typeof(StackPanel))
            };
            itemsPanelTemplate.VisualTree.SetValue(StackPanel.OrientationProperty, Orientation.Horizontal);
            listBox.ItemsPanel = itemsPanelTemplate;
            var dataTemplate = CreateDataTemplate();
            listBox.ItemTemplate = dataTemplate;
            return listBox;
        }
References MusicApp.Views.HomeView.CreateDataTemplate(), MusicApp.Views.HomeView.ListBox_ScrollChanged(), and MusicApp.Views.HomeView.RadioSongListBoxCommand().
Referenced by MusicApp.Views.HomeView.AddRandomSongsListBoxAsync(), and MusicApp.Views.HomeView.AddSongsFromAuthorListBoxAsync().
DynamicScrollViewer_ScrollChanged()
async void MusicApp.Views.HomeView.DynamicScrollViewer_ScrollChanged (object sender, ScrollChangedEventArgs e) [inline], [private]
Handles the ScrollChanged event for dynamically loading additional content as the user scrolls.
Definition at line 112 of file HomeView.xaml.cs.
        {
            // Check if the user is nearing the bottom of the scrollable area
            if (sender == DynamicScrollViewer && e.VerticalOffset + e.ViewportHeight >= e.ExtentHeight - 200)
            {
                if (!_isLoadingPanel)
                {
                    _isLoadingPanel = true;
                    await AddDynamicListBoxSectionAsync();
                    _isLoadingPanel = false;
                }
            }
        }
References MusicApp.Views.HomeView.AddDynamicListBoxSectionAsync().
ExecuteAddSongToPlaylist()
void MusicApp.Views.HomeView.ExecuteAddSongToPlaylist (object sender) [inline], [private]
Executes the command to add a song to a playlist from the context menu.
Definition at line 341 of file HomeView.xaml.cs.
        {
            var song = Utils.Utils.GetItemFromMenuItem<MySong>(sender);
            if (song != null)
            {
                var viewModel = DataContext as HomeViewModel;
                viewModel?._mainViewModel.PlayerViewModel.AddSongToPlaylistCommand.Execute(song);
            }
        }
Referenced by MusicApp.Views.HomeView.AddSongToPlaylist_ComboBox().
ExecuteDeletePlaylistCommand()
void MusicApp.Views.HomeView.ExecuteDeletePlaylistCommand (object sender) [inline], [private]
Executes the delete command for a playlist.
Definition at line 91 of file HomeView.xaml.cs.
        {
            var playlist = GetItemFromMenuItem<Playlist>(sender);
            if (playlist != null)
            {
                var viewModel = DataContext as HomeViewModel;
                viewModel?.DeletePlaylistCommand.Execute(playlist);
            }
        }
Referenced by MusicApp.Views.HomeView.RemovePlaylist_ComboBox().
GetRandomAuthor()
string? MusicApp.Views.HomeView.GetRandomAuthor (IEnumerable< MySong > songs) [inline], [private]
Gets a random author from the list of available songs.
Definition at line 331 of file HomeView.xaml.cs.
        {
            var authors = songs.SelectMany(song => song.Artists.Select(artist => artist.Name)).Distinct().ToList();
            if (authors.Count == 0) return null;
            return authors[_random.Next(authors.Count)];
        }
Referenced by MusicApp.Views.HomeView.AddSongsFromAuthorListBoxAsync().
GetRandomSongs()
async Task< ObservableCollection< MySong >?> MusicApp.Views.HomeView.GetRandomSongs () [inline], [private]
Gets a collection of random songs from the database for recommendation.
Definition at line 308 of file HomeView.xaml.cs.
        {
            var viewModel = DataContext as HomeViewModel;
            var randomSongIds = viewModel?._mainViewModel.SongDatabase?.GetSongsForRecommendation();
            if (randomSongIds == null || randomSongIds.Count == 0) return null;
            var fetchTasks = randomSongIds.Select(async songId =>
            {
                return MySong.Create(await MyYouTubeService.FetchSongVideoInfoAsync(songId));
            });
            var songs = await Task.WhenAll(fetchTasks);
            if (songs == null || songs.Length == 0) return null;
            var randomSongs = new ObservableCollection<MySong>(songs.Where(song => song != null));
            return randomSongs;
        }
References MusicApp.Models.MySong.Create(), MusicApp.Models.MyYouTubeService.FetchSongVideoInfoAsync(), and SongDatabase.GetSongsForRecommendation().
Referenced by MusicApp.Views.HomeView.AddRandomSongsListBoxAsync().
ListBox_ScrollChanged()
void MusicApp.Views.HomeView.ListBox_ScrollChanged (object sender, ScrollChangedEventArgs e) [inline], [private]
Prevents the ListBox from triggering the main ScrollViewer's event when scrolling.
Definition at line 129 of file HomeView.xaml.cs.
        {
            e.Handled = true;
        }
Referenced by MusicApp.Views.HomeView.CreateListBox().
ListViewScrollViewer_PreviewMouseWheel()
void MusicApp.Views.HomeView.ListViewScrollViewer_PreviewMouseWheel (object sender, MouseWheelEventArgs e) [inline], [private]
Handles the MouseWheel event for the ListView ScrollViewer to enable smooth scrolling.
Definition at line 51 of file HomeView.xaml.cs.
        {
            ScrollViewer scv = (ScrollViewer)sender;
            scv.ScrollToVerticalOffset(scv.VerticalOffset - e.Delta / 4);
            e.Handled = true;
        }
PlaylistListBoxItemCommand()
void MusicApp.Views.HomeView.PlaylistListBoxItemCommand (object sender, MouseButtonEventArgs e) [inline], [private]
Handles the MouseLeftButtonUp event for selecting a playlist.
Definition at line 61 of file HomeView.xaml.cs.
        {
            var viewModel = DataContext as HomeViewModel;
            viewModel?.SelectPlaylistCommand.Execute(null);
        }
PopularSongsListBoxCommand()
void MusicApp.Views.HomeView.PopularSongsListBoxCommand (object sender, MouseButtonEventArgs e) [inline], [private]
Handles the MouseLeftButtonUp event for playing a popular song.
Definition at line 82 of file HomeView.xaml.cs.
        {
            var viewModel = DataContext as HomeViewModel;
            viewModel?.SelectPopularSongCommand.Execute(null);
        }
RadioSongListBoxCommand()
async void MusicApp.Views.HomeView.RadioSongListBoxCommand (object sender, MouseButtonEventArgs e, ObservableCollection< MySong > songs, int index) [inline], [private]
Handles the MouseLeftButtonUp event for playing a song from the radio list.
Definition at line 70 of file HomeView.xaml.cs.
        {
            var viewModel = DataContext as HomeViewModel;
            if (viewModel != null)
            {
                await viewModel.HandleRadioSongSelection(songs, index);
            }
        }
References MusicApp.ViewModels.HomeViewModel.HandleRadioSongSelection().
Referenced by MusicApp.Views.HomeView.CreateListBox().
RemovePlaylist_ComboBox()
void MusicApp.Views.HomeView.RemovePlaylist_ComboBox (object sender, RoutedEventArgs e) [inline], [private]
Handles the Click event for removing a playlist using a context menu.
Definition at line 104 of file HomeView.xaml.cs.
        {
            ExecuteDeletePlaylistCommand(sender);
        }
References MusicApp.Views.HomeView.ExecuteDeletePlaylistCommand().
TextBox_KeyDown()
void MusicApp.Views.HomeView.TextBox_KeyDown (object sender, KeyEventArgs e) [inline], [private]
Handles the KeyDown event for the search TextBox, triggering the search command when Enter is pressed.
Definition at line 39 of file HomeView.xaml.cs.
        {
            if (e.Key == Key.Enter)
            {
                var viewModel = DataContext as HomeViewModel;
                viewModel?.SearchCommand.Execute(null);
            }
        }
Member Data Documentation
_isLoadingPanel
bool MusicApp.Views.HomeView._isLoadingPanel = false [private]
Definition at line 28 of file HomeView.xaml.cs.
_random
readonly Random MusicApp.Views.HomeView._random = new() [private]
Definition at line 29 of file HomeView.xaml.cs.
The documentation for this class was generated from the following file:
Views/HomeView.xaml.cs