SongDatabase Class Reference
Public Member Functions
SongDatabase (string databasePath)
Initializes a new instance of the SongDatabase class.
void InsertSong (string id)
Inserts a new song into the Songs table with an initial count of 0. If the song already exists, the operation is ignored.
void UpdateSongCount (string id)
Increments the count of a song in the Songs table by 1.
int GetSongCount (string id)
Retrieves the current count of a song from the Songs table.
List< string > GetSongsForRecommendation ()
Retrieves 5 songs with the lowest count and 5 random songs from the Songs table. Also increments the count of each selected song by 1.
void IncreaseSongCount (string id)
Increases the count of a song by 1.
Private Member Functions
void CreateTable ()
Creates the Songs table in the database if it doesn't exist.
Private Attributes
readonly string _connectionString
Detailed Description
Definition at line 6 of file SongDatabase.cs.
Constructor & Destructor Documentation
SongDatabase()
SongDatabase.SongDatabase (string databasePath) [inline]
Initializes a new instance of the SongDatabase class.
Parameters
databasePath The path to the SQLite database file.
Definition at line 14 of file SongDatabase.cs.
    {
        _connectionString = $"Data Source={databasePath};";
        CreateTable();
    }
References CreateTable().
Member Function Documentation
CreateTable()
void SongDatabase.CreateTable () [inline], [private]
Creates the Songs table in the database if it doesn't exist.
Definition at line 23 of file SongDatabase.cs.
    {
        using (var connection = new SQLiteConnection(_connectionString))
        {
            connection.Open();
            string createTableQuery = @"
                CREATE TABLE IF NOT EXISTS Songs (
                    Id TEXT PRIMARY KEY,
                    Count INTEGER DEFAULT 0
                )";
            using (var command = new SQLiteCommand(createTableQuery, connection))
            {
                command.ExecuteNonQuery();
            }
        }
    }
Referenced by SongDatabase().
GetSongCount()
int SongDatabase.GetSongCount (string id) [inline]
Retrieves the current count of a song from the Songs table.
Parameters
id The unique identifier of the song.
Returns
The count of the song, or 0 if the song does not exist.
Definition at line 94 of file SongDatabase.cs.
    {
        using (var connection = new SQLiteConnection(_connectionString))
        {
            connection.Open();
            string selectQuery = "SELECT Count FROM Songs WHERE Id = @id";
            using (var command = new SQLiteCommand(selectQuery, connection))
            {
                command.Parameters.AddWithValue("@id", id);
                var result = command.ExecuteScalar();
                return result != null ? Convert.ToInt32(result) : 0;
            }
        }
    }
GetSongsForRecommendation()
List< string > SongDatabase.GetSongsForRecommendation () [inline]
Retrieves 5 songs with the lowest count and 5 random songs from the Songs table. Also increments the count of each selected song by 1.
Returns
A list of song IDs for recommendation.
Definition at line 116 of file SongDatabase.cs.
    {
        using (var connection = new SQLiteConnection(_connectionString))
        {
            connection.Open();
            // Get 5 songs with the lowest count
            string queryLowestCount = @"
            SELECT Id
            FROM Songs
            ORDER BY Count ASC
            LIMIT 5";
            var songIds = new List<string>();
            using (var command = new SQLiteCommand(queryLowestCount, connection))
            {
                using (var reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        songIds.Add(reader.GetString(0));
                    }
                }
            }
            // Get 5 random songs, excluding those with the lowest count
            string queryRandomSongs = @"
            SELECT Id
            FROM Songs
            WHERE Id NOT IN (" + string.Join(",", songIds.Select(id => $"'{id}'")) + @")
            ORDER BY RANDOM()
            LIMIT 5";
            using (var command = new SQLiteCommand(queryRandomSongs, connection))
            {
                using (var reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        songIds.Add(reader.GetString(0));
                    }
                }
            }
            // Increment the count for each selected song
            string queryIncrementCount = @"
            UPDATE Songs
            SET Count = Count + 1
            WHERE Id = @Id";
            foreach (var songId in songIds)
            {
                using (var updateCommand = new SQLiteCommand(queryIncrementCount, connection))
                {
                    updateCommand.Parameters.AddWithValue("@Id", songId);
                    updateCommand.ExecuteNonQuery();
                }
            }
            return songIds;
        }
    }
Referenced by MusicApp.Views.HomeView.GetRandomSongs().
IncreaseSongCount()
void SongDatabase.IncreaseSongCount (string id) [inline]
Increases the count of a song by 1.
Parameters
id The unique identifier of the song.
Definition at line 184 of file SongDatabase.cs.
    {
        UpdateSongCount(id);
    }
References UpdateSongCount().
InsertSong()
void SongDatabase.InsertSong (string id) [inline]
Inserts a new song into the Songs table with an initial count of 0. If the song already exists, the operation is ignored.
Parameters
id The unique identifier of the song.
Definition at line 47 of file SongDatabase.cs.
    {
        using (var connection = new SQLiteConnection(_connectionString))
        {
            connection.Open();
            string insertQuery = @"
                INSERT INTO Songs (Id, Count)
                VALUES (@id, 0)
                ON CONFLICT(Id) DO NOTHING";
            using (var command = new SQLiteCommand(insertQuery, connection))
            {
                command.Parameters.AddWithValue("@id", id);
                command.ExecuteNonQuery();
            }
        }
    }
UpdateSongCount()
void SongDatabase.UpdateSongCount (string id) [inline]
Increments the count of a song in the Songs table by 1.
Parameters
id The unique identifier of the song.
Definition at line 70 of file SongDatabase.cs.
    {
        using (var connection = new SQLiteConnection(_connectionString))
        {
            connection.Open();
            string updateQuery = @"
                UPDATE Songs
                SET Count = Count + 1
                WHERE Id = @id";
            using (var command = new SQLiteCommand(updateQuery, connection))
            {
                command.Parameters.AddWithValue("@id", id);
                command.ExecuteNonQuery();
            }
        }
    }
Referenced by IncreaseSongCount().
Member Data Documentation
_connectionString
readonly string SongDatabase._connectionString [private]
Definition at line 8 of file SongDatabase.cs.
The documentation for this class was generated from the following file:
Models/SongDatabase.cs