MusicApp.ViewModels.HomeViewModel Class Reference
ViewModel for the HomeView, responsible for managing playlists, popular songs, and handling user interactions.
Public Member Functions
void ResetIndices ()
Resets the selected indices for playlists and popular songs.
HomeViewModel (MainViewModel mainViewModel)
Initializes a new instance of the HomeViewModel class.
async Task HandleRadioSongSelection (ObservableCollection< MySong > Songs, int index)
Handles the selection of a radio song asynchronously.
Public Member Functions inherited from MusicApp.ViewModels.BaseViewModel
void SetPreviousViewModel (BaseViewModel previousViewModel)
Sets the previous ViewModel for navigation purposes.
BaseViewModel GetPreviousViewModel ()
Gets the previous ViewModel for navigation purposes.
Public Attributes
readonly MainViewModel _mainViewModel
Properties
ObservableCollection< MySong > AllPlaylistSongs [get, set]
Gets or sets the collection of all songs from all playlists.
int SelectedPopularSongIndex [get, set]
Gets or sets the index of the selected popular song.
MyShelf< MySong > PopularSongs [get, set]
Gets or sets the collection of popular songs.
Playlist SelectedPlaylist [get, set]
Gets or sets the selected playlist.
int SelectedPlaylistIndex [get, set]
Gets or sets the index of the selected playlist.
string SearchQuery [get, set]
Gets or sets the search query string.
ObservableCollection< Playlist > Playlists [get, set]
Gets or sets the collection of playlists.
ICommand SearchCommand [get]
ICommand AddPlaylistCommand [get]
ICommand SelectPlaylistCommand [get]
ICommand SelectPopularSongCommand [get]
ICommand DeletePlaylistCommand [get]
Private Member Functions
async void LoadData ()
Loads playlists and popular songs asynchronously.
async Task LoadPopularSongs ()
Loads popular songs asynchronously.
async Task LoadPlaylists ()
Loads playlists asynchronously.
async Task LoadAllPlaylistSongs ()
Loads all songs from all playlists asynchronously.
async Task HandlePlaylistSelectionAsync ()
Handles the selection of a playlist asynchronously.
void HandlePopularSongSelection ()
Handles the selection of a popular song.
async Task ExecuteSearch ()
Executes the search command asynchronously.
void OpenAddPlaylistDialog (object parameter)
Opens the Add Playlist dialog.
async void AddNewPlaylist (string title, string description, bool isPublic)
Adds a new playlist asynchronously.
void ExecuteDeletePlaylist (object parameter)
Executes the delete playlist command.
async void DeletePlaylist (Playlist playlist)
Deletes a playlist asynchronously.
Private Attributes
string _searchQuery = string.Empty
ObservableCollection< Playlist > _playlists = new()
Playlist _selectedPlaylist = new()
int _selectedPlaylistIndex = -1
MyShelf< MySong > _popularSongs = new MyShelf<MySong>(new(), null)
int _selectedPopularSongIndex = -1
string? _popularSongsContinuationToken
ObservableCollection< MySong > _allPlaylistSongs = new()
Additional Inherited Members
Protected Member Functions inherited from MusicApp.ViewModels.BaseViewModel
void OnPropertyChanged ([CallerMemberName] string propertyName=null)
Raises the PropertyChanged event to notify the UI of a property value change.
bool SetProperty< T > (ref T field, T value, [CallerMemberName] string propertyName=null)
Sets the specified property if the value is different, and raises the PropertyChanged event.
Events inherited from MusicApp.ViewModels.BaseViewModel
PropertyChangedEventHandler PropertyChanged
Occurs when a property value changes.
Detailed Description
ViewModel for the HomeView, responsible for managing playlists, popular songs, and handling user interactions.
Definition at line 17 of file HomeViewModel.cs.
Constructor & Destructor Documentation
HomeViewModel()
MusicApp.ViewModels.HomeViewModel.HomeViewModel (MainViewModel mainViewModel) [inline]
Initializes a new instance of the HomeViewModel class.
Parameters
mainViewModel The main ViewModel instance.
Definition at line 122 of file HomeViewModel.cs.
        {
            _mainViewModel = mainViewModel;
            SearchCommand = new RelayCommand(async _ => await ExecuteSearch());
            AddPlaylistCommand = new RelayCommand(OpenAddPlaylistDialog);
            SelectPlaylistCommand = new RelayCommand(async _ => await HandlePlaylistSelectionAsync());
            SelectPopularSongCommand = new RelayCommand(_ => HandlePopularSongSelection());
            DeletePlaylistCommand = new RelayCommand(ExecuteDeletePlaylist);
            LoadData();
        }
References MusicApp.ViewModels.HomeViewModel.ExecuteDeletePlaylist(), MusicApp.ViewModels.HomeViewModel.ExecuteSearch(), MusicApp.ViewModels.HomeViewModel.HandlePlaylistSelectionAsync(), MusicApp.ViewModels.HomeViewModel.HandlePopularSongSelection(), MusicApp.ViewModels.HomeViewModel.LoadData(), and MusicApp.ViewModels.HomeViewModel.OpenAddPlaylistDialog().
Member Function Documentation
AddNewPlaylist()
async void MusicApp.ViewModels.HomeViewModel.AddNewPlaylist (string title, string description, bool isPublic) [inline], [private]
Adds a new playlist asynchronously.
Parameters
title The title of the new playlist.
description The description of the new playlist.
isPublic Indicates whether the playlist is public.
Definition at line 297 of file HomeViewModel.cs.
        {
            try
            {
                var privacyStatus = isPublic ? "public" : "private";
                await _mainViewModel.MyYouTubeService.AddNewPlaylist(title, description, privacyStatus);
                await Task.Delay(5000); // Wait for the playlist to be created
                await LoadPlaylists();
            }
            catch (Google.GoogleApiException ex)
            {
                MessageBox.Show($"An API error occurred: {ex.Message}\n{ex.Error.Message}");
            }
            catch (Exception ex)
            {
                MessageBox.Show($"An error occurred: {ex.Message}");
            }
        }
References MusicApp.ViewModels.HomeViewModel.LoadPlaylists().
Referenced by MusicApp.ViewModels.HomeViewModel.OpenAddPlaylistDialog().
DeletePlaylist()
async void MusicApp.ViewModels.HomeViewModel.DeletePlaylist (Playlist playlist) [inline], [private]
Deletes a playlist asynchronously.
Parameters
playlist The playlist to delete.
Definition at line 338 of file HomeViewModel.cs.
        {
            if (playlist == null)
            {
                return;
            }
            var index = Playlists.IndexOf(playlist);
            try
            {
                await _mainViewModel.MyYouTubeService.DeletePlaylistAsync(playlist.Id);
                Playlists.RemoveAt(index);
            }
            catch (Google.GoogleApiException ex)
            {
                MessageBox.Show($"An API error occurred: {ex.Message}\n{ex.Error.Message}");
            }
            catch (Exception ex)
            {
                MessageBox.Show($"An error occurred: {ex.Message}");
            }
        }
References MusicApp.ViewModels.HomeViewModel.Playlists.
Referenced by MusicApp.ViewModels.HomeViewModel.ExecuteDeletePlaylist().
ExecuteDeletePlaylist()
void MusicApp.ViewModels.HomeViewModel.ExecuteDeletePlaylist (object parameter) [inline], [private]
Executes the delete playlist command.
Parameters
parameter The command parameter.
Definition at line 322 of file HomeViewModel.cs.
        {
            if (parameter is Playlist playlist)
            {
                var result = MessageBox.Show($"Are you sure you want to delete the playlist \"{playlist.Snippet.Title}\"?", "Confirm Deletion", MessageBoxButton.YesNo, MessageBoxImage.Warning);
                if (result == MessageBoxResult.Yes)
                {
                    DeletePlaylist(playlist);
                }
            }
        }
References MusicApp.ViewModels.HomeViewModel.DeletePlaylist().
Referenced by MusicApp.ViewModels.HomeViewModel.HomeViewModel().
ExecuteSearch()
async Task MusicApp.ViewModels.HomeViewModel.ExecuteSearch () [inline], [private]
Executes the search command asynchronously.
Definition at line 269 of file HomeViewModel.cs.
        {
            if (!string.IsNullOrWhiteSpace(SearchQuery))
            {
                _mainViewModel.SearchViewModel.SearchQuery = SearchQuery;
                await _mainViewModel.SearchAndNavigateAsync(SearchQuery);
            }
        }
References MusicApp.ViewModels.HomeViewModel.SearchQuery.
Referenced by MusicApp.ViewModels.HomeViewModel.HomeViewModel().
HandlePlaylistSelectionAsync()
async Task MusicApp.ViewModels.HomeViewModel.HandlePlaylistSelectionAsync () [inline], [private]
Handles the selection of a playlist asynchronously.
Definition at line 192 of file HomeViewModel.cs.
        {
            try
            {
                if (Playlists.ElementAtOrDefault(SelectedPlaylistIndex) is Playlist playlist)
                {
                    var playlistItems = await _mainViewModel.MyYouTubeService.FetchPlaylistContentAsync(playlist.Id);
                    if (playlistItems == null)
                    {
                        MessageBox.Show("Failed to fetch playlist content.");
                        return;
                    }
                    else if (playlistItems.Count == 0)
                    {
                        MessageBox.Show("This playlist is empty.");
                        return;
                    }
                    _mainViewModel.ResetIndices();
                    _mainViewModel.CurrentMusicSource = MainViewModel.MusicSource.Playlist;
                    _mainViewModel.PlayerViewModel.ProvidePlayerInfo(playlistItems, 0, GetInfoString(playlist.Snippet.Title));
                    _mainViewModel.SwitchToPlayerView();
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }
References MusicApp.ViewModels.HomeViewModel.Playlists, and MusicApp.ViewModels.HomeViewModel.SelectedPlaylistIndex.
Referenced by MusicApp.ViewModels.HomeViewModel.HomeViewModel().
HandlePopularSongSelection()
void MusicApp.ViewModels.HomeViewModel.HandlePopularSongSelection () [inline], [private]
Handles the selection of a popular song.
Definition at line 256 of file HomeViewModel.cs.
        {
            if (PopularSongs.Items.ElementAtOrDefault(SelectedPopularSongIndex) is MySong song)
            {
                _mainViewModel.CurrentMusicSource = MainViewModel.MusicSource.Popular;
                _mainViewModel.PlayerViewModel.ProvidePlayerInfo(PopularSongs.Items, SelectedPopularSongIndex, GetInfoString("Popular Songs"), _popularSongsContinuationToken);
                _mainViewModel.SwitchToPlayerView();
            }
        }
References MusicApp.Models.MyShelf< T >.Items, MusicApp.ViewModels.HomeViewModel.PopularSongs, and MusicApp.ViewModels.HomeViewModel.SelectedPopularSongIndex.
Referenced by MusicApp.ViewModels.HomeViewModel.HomeViewModel().
HandleRadioSongSelection()
async Task MusicApp.ViewModels.HomeViewModel.HandleRadioSongSelection (ObservableCollection< MySong > Songs, int index) [inline]
Handles the selection of a radio song asynchronously.
Parameters
Songs The collection of songs to play.
index The index of the selected song.
Definition at line 227 of file HomeViewModel.cs.
        {
            if (Songs.ElementAtOrDefault(index) is MySong song and not null)
            {
                var newSongs = new ObservableCollection<MySong>() { song };
                var radioPlaylistId = await song.GetPlaylistIdAsync();
                var radioSongs = await _mainViewModel.MyYouTubeService.FetchRadioSongsAsync(radioPlaylistId);
                _mainViewModel.ResetIndices();
                _mainViewModel.CurrentMusicSource = MainViewModel.MusicSource.Search;
                if (radioSongs == null)
                {
                    MessageBox.Show("No songs found.");
                    return;
                }
                foreach (var item in radioSongs)
                {
                    newSongs.Add(item);
                }
                _mainViewModel.PlayerViewModel.ProvidePlayerInfo(newSongs, 0, GetInfoString($"Radio {song.Name}"));
                _mainViewModel.SwitchToPlayerView();
            }
        }
Referenced by MusicApp.Views.HomeView.RadioSongListBoxCommand().
LoadAllPlaylistSongs()
async Task MusicApp.ViewModels.HomeViewModel.LoadAllPlaylistSongs () [inline], [private]
Loads all songs from all playlists asynchronously.
Definition at line 167 of file HomeViewModel.cs.
        {
            var allSongs = new ObservableCollection<MySong>();
            var tasks = Playlists.Select(async playlist =>
            {
                var playlistItems = await _mainViewModel.MyYouTubeService.FetchPlaylistContentAsync(playlist.Id);
                if (playlistItems != null)
                {
                    foreach (var song in playlistItems)
                    {
                        Application.Current.Dispatcher.Invoke(() => allSongs.Add(song));
                        _mainViewModel.SongDatabase?.InsertSong(song.Id);
                    }
                }
            });
            await Task.WhenAll(tasks);
            AllPlaylistSongs = allSongs;
        }
References MusicApp.ViewModels.HomeViewModel.AllPlaylistSongs, and MusicApp.ViewModels.HomeViewModel.Playlists.
Referenced by MusicApp.ViewModels.HomeViewModel.LoadData().
LoadData()
async void MusicApp.ViewModels.HomeViewModel.LoadData () [inline], [private]
Loads playlists and popular songs asynchronously.
Definition at line 136 of file HomeViewModel.cs.
        {
            var loadPlaylistsTask = LoadPlaylists();
            var loadPopularSongsTask = LoadPopularSongs();
            // Start loading both playlists and popular songs concurrently
            await Task.WhenAll(loadPlaylistsTask, loadPopularSongsTask);
            await LoadAllPlaylistSongs();
        }
References MusicApp.ViewModels.HomeViewModel.LoadAllPlaylistSongs(), MusicApp.ViewModels.HomeViewModel.LoadPlaylists(), and MusicApp.ViewModels.HomeViewModel.LoadPopularSongs().
Referenced by MusicApp.ViewModels.HomeViewModel.HomeViewModel().
LoadPlaylists()
async Task MusicApp.ViewModels.HomeViewModel.LoadPlaylists () [inline], [private]
Loads playlists asynchronously.
Definition at line 158 of file HomeViewModel.cs.
        {
            var playlists = await _mainViewModel.MyYouTubeService.FetchAllPlaylistsAsync();
            Playlists = playlists;
        }
References MusicApp.ViewModels.HomeViewModel.Playlists.
Referenced by MusicApp.ViewModels.HomeViewModel.AddNewPlaylist(), and MusicApp.ViewModels.HomeViewModel.LoadData().
LoadPopularSongs()
async Task MusicApp.ViewModels.HomeViewModel.LoadPopularSongs () [inline], [private]
Loads popular songs asynchronously.
Definition at line 149 of file HomeViewModel.cs.
        {
            var popularSongs = await _mainViewModel.MyYouTubeService.FetchPopularSongsAsync(null);
            PopularSongs = popularSongs;
        }
References MusicApp.ViewModels.HomeViewModel.PopularSongs.
Referenced by MusicApp.ViewModels.HomeViewModel.LoadData().
OpenAddPlaylistDialog()
void MusicApp.ViewModels.HomeViewModel.OpenAddPlaylistDialog (object parameter) [inline], [private]
Opens the Add Playlist dialog.
Parameters
parameter The command parameter.
Definition at line 282 of file HomeViewModel.cs.
        {
            var dialog = new AddPlaylistDialog();
            if (dialog.ShowDialog() == true)
            {
                AddNewPlaylist(dialog.PlaylistName, dialog.PlaylistDescription, dialog.PlaylistVisibility == "Public");
            }
        }
References MusicApp.ViewModels.HomeViewModel.AddNewPlaylist().
Referenced by MusicApp.ViewModels.HomeViewModel.HomeViewModel().
ResetIndices()
void MusicApp.ViewModels.HomeViewModel.ResetIndices () [inline]
Resets the selected indices for playlists and popular songs.
Definition at line 42 of file HomeViewModel.cs.
        {
            SelectedPlaylistIndex = -1;
            SelectedPopularSongIndex = -1;
        }
References MusicApp.ViewModels.HomeViewModel.SelectedPlaylistIndex, and MusicApp.ViewModels.HomeViewModel.SelectedPopularSongIndex.
Referenced by MusicApp.ViewModels.MainViewModel.ResetIndices().
Member Data Documentation
_allPlaylistSongs
ObservableCollection<MySong> MusicApp.ViewModels.HomeViewModel._allPlaylistSongs = new() [private]
Definition at line 28 of file HomeViewModel.cs.
_mainViewModel
readonly MainViewModel MusicApp.ViewModels.HomeViewModel._mainViewModel
Definition at line 19 of file HomeViewModel.cs.
_playlists
ObservableCollection<Playlist> MusicApp.ViewModels.HomeViewModel._playlists = new() [private]
Definition at line 21 of file HomeViewModel.cs.
_popularSongs
MyShelf<MySong> MusicApp.ViewModels.HomeViewModel._popularSongs = new MyShelf<MySong>(new(), null) [private]
Definition at line 24 of file HomeViewModel.cs.
_popularSongsContinuationToken
string? MusicApp.ViewModels.HomeViewModel._popularSongsContinuationToken [private]
Definition at line 26 of file HomeViewModel.cs.
_searchQuery
string MusicApp.ViewModels.HomeViewModel._searchQuery = string.Empty [private]
Definition at line 20 of file HomeViewModel.cs.
_selectedPlaylist
Playlist MusicApp.ViewModels.HomeViewModel._selectedPlaylist = new() [private]
Definition at line 22 of file HomeViewModel.cs.
_selectedPlaylistIndex
int MusicApp.ViewModels.HomeViewModel._selectedPlaylistIndex = -1 [private]
Definition at line 23 of file HomeViewModel.cs.
_selectedPopularSongIndex
int MusicApp.ViewModels.HomeViewModel._selectedPopularSongIndex = -1 [private]
Definition at line 25 of file HomeViewModel.cs.
Property Documentation
AddPlaylistCommand
ICommand MusicApp.ViewModels.HomeViewModel.AddPlaylistCommand [get]
Definition at line 113 of file HomeViewModel.cs.
{ get; }
AllPlaylistSongs
ObservableCollection<MySong> MusicApp.ViewModels.HomeViewModel.AllPlaylistSongs [get], [set]
Gets or sets the collection of all songs from all playlists.
Definition at line 33 of file HomeViewModel.cs.
        {
            get => _allPlaylistSongs;
            set => SetProperty(ref _allPlaylistSongs, value);
        }
Referenced by MusicApp.ViewModels.HomeViewModel.LoadAllPlaylistSongs().
DeletePlaylistCommand
ICommand MusicApp.ViewModels.HomeViewModel.DeletePlaylistCommand [get]
Definition at line 116 of file HomeViewModel.cs.
{ get; }
Playlists
ObservableCollection<Playlist> MusicApp.ViewModels.HomeViewModel.Playlists [get], [set]
Gets or sets the collection of playlists.
Definition at line 106 of file HomeViewModel.cs.
        {
            get => _playlists;
            set => SetProperty(ref _playlists, value);
        }
Referenced by MusicApp.ViewModels.HomeViewModel.DeletePlaylist(), MusicApp.ViewModels.HomeViewModel.HandlePlaylistSelectionAsync(), MusicApp.ViewModels.HomeViewModel.LoadAllPlaylistSongs(), and MusicApp.ViewModels.HomeViewModel.LoadPlaylists().
PopularSongs
MyShelf<MySong> MusicApp.ViewModels.HomeViewModel.PopularSongs [get], [set]
Gets or sets the collection of popular songs.
Definition at line 63 of file HomeViewModel.cs.
        {
            get => _popularSongs;
            set => SetProperty(ref _popularSongs, value);
        }
Referenced by MusicApp.ViewModels.HomeViewModel.HandlePopularSongSelection(), and MusicApp.ViewModels.HomeViewModel.LoadPopularSongs().
SearchCommand
ICommand MusicApp.ViewModels.HomeViewModel.SearchCommand [get]
Definition at line 112 of file HomeViewModel.cs.
{ get; }
SearchQuery
string MusicApp.ViewModels.HomeViewModel.SearchQuery [get], [set]
Gets or sets the search query string.
Definition at line 97 of file HomeViewModel.cs.
        {
            get => _searchQuery;
            set => SetProperty(ref _searchQuery, value);
        }
Referenced by MusicApp.ViewModels.HomeViewModel.ExecuteSearch().
SelectedPlaylist
Playlist MusicApp.ViewModels.HomeViewModel.SelectedPlaylist [get], [set]
Gets or sets the selected playlist.
Definition at line 72 of file HomeViewModel.cs.
        {
            get => _selectedPlaylist;
            set => SetProperty(ref _selectedPlaylist, value);
        }
SelectedPlaylistIndex
int MusicApp.ViewModels.HomeViewModel.SelectedPlaylistIndex [get], [set]
Gets or sets the index of the selected playlist.
Definition at line 81 of file HomeViewModel.cs.
        {
            get => _selectedPlaylistIndex;
            set
            {
                SetProperty(ref _selectedPlaylistIndex, value);
                if (value >= 0 && value < Playlists.Count)
                {
                    SelectedPlaylist = Playlists[value];
                }
            }
        }
Referenced by MusicApp.ViewModels.HomeViewModel.HandlePlaylistSelectionAsync(), and MusicApp.ViewModels.HomeViewModel.ResetIndices().
SelectedPopularSongIndex
int MusicApp.ViewModels.HomeViewModel.SelectedPopularSongIndex [get], [set]
Gets or sets the index of the selected popular song.
Definition at line 51 of file HomeViewModel.cs.
        {
            get => _selectedPopularSongIndex;
            set
            {
                SetProperty(ref _selectedPopularSongIndex, value);
            }
        }
Referenced by MusicApp.ViewModels.HomeViewModel.HandlePopularSongSelection(), and MusicApp.ViewModels.HomeViewModel.ResetIndices().
SelectPlaylistCommand
ICommand MusicApp.ViewModels.HomeViewModel.SelectPlaylistCommand [get]
Definition at line 114 of file HomeViewModel.cs.
{ get; }
SelectPopularSongCommand
ICommand MusicApp.ViewModels.HomeViewModel.SelectPopularSongCommand [get]
Definition at line 115 of file HomeViewModel.cs.
{ get; }
The documentation for this class was generated from the following file:
ViewModels/HomeViewModel.cs