MusicApp.Views.PlayerView Class Reference
Interaction logic for PlayerView.xaml. This class handles the interactions for the player view.
Public Member Functions
PlayerView ()
Initializes a new instance of the PlayerView class.
Private Member Functions
void TrackBarSeek_PreviewMouseLeftButtonDown (object sender, MouseButtonEventArgs e)
Handles the PreviewMouseLeftButtonDown event for the track bar (seek slider). Begins the seek operation.
void TrackBarSeek_PreviewMouseLeftButtonUp (object sender, MouseButtonEventArgs e)
Handles the PreviewMouseLeftButtonUp event for the track bar (seek slider). Ends the seek operation.
void TrackBarSeek_ValueChanged (object sender, RoutedPropertyChangedEventArgs< double > e)
Handles the ValueChanged event for the track bar (seek slider). Updates the current position in the media.
void ExecuteAddSongToPlaylist (object sender)
Executes the AddSongToPlaylist command when the context menu item is clicked.
void AddSongToPlaylist_ComboBox (object sender, RoutedEventArgs e)
Handles the RoutedEvent for adding a song to a playlist from the context menu.
void ExecuteRemoveSongFromPlaylist (object sender)
Executes the RemoveSongFromPlaylist command when the context menu item is clicked.
void RemoveSongFromPlaylist (object sender, RoutedEventArgs e)
Handles the RoutedEvent for removing a song from a playlist from the context menu.
void PreviewMouseRightButtonDown_IgnoreIndexSelection (object sender, MouseButtonEventArgs e)
Handles the PreviewMouseRightButtonDown event to prevent the selection index from changing. This is useful for context menu operations where the selection should remain unchanged.
void Button_PreviewKeyDown (object sender, KeyEventArgs e)
Handles the PreviewKeyDown event for buttons to suppress the Enter and Spacebar key presses. This prevents unintended command execution from these keys.
Detailed Description
Interaction logic for PlayerView.xaml. This class handles the interactions for the player view.
Definition at line 13 of file PlayerView.xaml.cs.
Constructor & Destructor Documentation
PlayerView()
MusicApp.Views.PlayerView.PlayerView () [inline]
Initializes a new instance of the PlayerView class.
Definition at line 18 of file PlayerView.xaml.cs.
        {
            InitializeComponent();
        }
Member Function Documentation
AddSongToPlaylist_ComboBox()
void MusicApp.Views.PlayerView.AddSongToPlaylist_ComboBox (object sender, RoutedEventArgs e) [inline], [private]
Handles the RoutedEvent for adding a song to a playlist from the context menu.
Parameters
sender The source of the event.
e The RoutedEventArgs containing event data.
Definition at line 85 of file PlayerView.xaml.cs.
        {
            ExecuteAddSongToPlaylist(sender);
        }
References MusicApp.Views.PlayerView.ExecuteAddSongToPlaylist().
Button_PreviewKeyDown()
void MusicApp.Views.PlayerView.Button_PreviewKeyDown (object sender, KeyEventArgs e) [inline], [private]
Handles the PreviewKeyDown event for buttons to suppress the Enter and Spacebar key presses. This prevents unintended command execution from these keys.
Parameters
sender The source of the event.
e The KeyEventArgs containing event data.
Definition at line 133 of file PlayerView.xaml.cs.
        {
            if (e.Key == Key.Enter || e.Key == Key.Space)
            {
                e.Handled = true; // Suppress the Enter and Spacebar key presses
            }
        }
ExecuteAddSongToPlaylist()
void MusicApp.Views.PlayerView.ExecuteAddSongToPlaylist (object sender) [inline], [private]
Executes the AddSongToPlaylist command when the context menu item is clicked.
Parameters
sender The source of the event, typically the MenuItem.
Definition at line 69 of file PlayerView.xaml.cs.
        {
            var song = Utils.Utils.GetItemFromMenuItem<MySong>(sender);
            if (song != null)
            {
                var viewModel = DataContext as PlayerViewModel;
                viewModel?.AddSongToPlaylistCommand.Execute(song);
            }
        }
Referenced by MusicApp.Views.PlayerView.AddSongToPlaylist_ComboBox().
ExecuteRemoveSongFromPlaylist()
void MusicApp.Views.PlayerView.ExecuteRemoveSongFromPlaylist (object sender) [inline], [private]
Executes the RemoveSongFromPlaylist command when the context menu item is clicked.
Parameters
sender The source of the event, typically the MenuItem.
Definition at line 94 of file PlayerView.xaml.cs.
        {
            var song = Utils.Utils.GetItemFromMenuItem<MySong>(sender);
            if (song != null)
            {
                var viewModel = DataContext as PlayerViewModel;
                viewModel?.RemoveSongFromPlaylistCommand.Execute(song);
            }
        }
Referenced by MusicApp.Views.PlayerView.RemoveSongFromPlaylist().
PreviewMouseRightButtonDown_IgnoreIndexSelection()
void MusicApp.Views.PlayerView.PreviewMouseRightButtonDown_IgnoreIndexSelection (object sender, MouseButtonEventArgs e) [inline], [private]
Handles the PreviewMouseRightButtonDown event to prevent the selection index from changing. This is useful for context menu operations where the selection should remain unchanged.
Parameters
sender The source of the event.
e The MouseButtonEventArgs containing event data.
Definition at line 121 of file PlayerView.xaml.cs.
        {
            // Mark the event as handled so the SelectedIndex doesn't change
            e.Handled = true;
        }
RemoveSongFromPlaylist()
void MusicApp.Views.PlayerView.RemoveSongFromPlaylist (object sender, RoutedEventArgs e) [inline], [private]
Handles the RoutedEvent for removing a song from a playlist from the context menu.
Parameters
sender The source of the event.
e The RoutedEventArgs containing event data.
Definition at line 110 of file PlayerView.xaml.cs.
        {
            ExecuteRemoveSongFromPlaylist(sender);
        }
References MusicApp.Views.PlayerView.ExecuteRemoveSongFromPlaylist().
TrackBarSeek_PreviewMouseLeftButtonDown()
void MusicApp.Views.PlayerView.TrackBarSeek_PreviewMouseLeftButtonDown (object sender, MouseButtonEventArgs e) [inline], [private]
Handles the PreviewMouseLeftButtonDown event for the track bar (seek slider). Begins the seek operation.
Parameters
sender The source of the event.
e The MouseButtonEventArgs containing event data.
Definition at line 29 of file PlayerView.xaml.cs.
        {
            if (DataContext is PlayerViewModel viewModel)
            {
                viewModel.TrackBarSeek_PreviewMouseLeftButtonDown(sender, e);
            }
        }
TrackBarSeek_PreviewMouseLeftButtonUp()
void MusicApp.Views.PlayerView.TrackBarSeek_PreviewMouseLeftButtonUp (object sender, MouseButtonEventArgs e) [inline], [private]
Handles the PreviewMouseLeftButtonUp event for the track bar (seek slider). Ends the seek operation.
Parameters
sender The source of the event.
e The MouseButtonEventArgs containing event data.
Definition at line 43 of file PlayerView.xaml.cs.
        {
            if (DataContext is PlayerViewModel viewModel)
            {
                viewModel.TrackBarSeek_PreviewMouseLeftButtonUp(sender, e);
            }
        }
TrackBarSeek_ValueChanged()
void MusicApp.Views.PlayerView.TrackBarSeek_ValueChanged (object sender, RoutedPropertyChangedEventArgs< double > e) [inline], [private]
Handles the ValueChanged event for the track bar (seek slider). Updates the current position in the media.
Parameters
sender The source of the event.
e The RoutedPropertyChangedEventArgs containing event data.
Definition at line 57 of file PlayerView.xaml.cs.
        {
            if (DataContext is PlayerViewModel viewModel)
            {
                viewModel.TrackBarSeek_ValueChanged(sender, e);
            }
        }
The documentation for this class was generated from the following file:
Views/PlayerView.xaml.cs